### ISSUE TITLE
Updating library issue 

### ISSUE THREAD

**Issue by VAVANOZ** [kodjodevf/mangayomi#100]
### Steps to reproduce

Can't see any option to update library 

### Expected behavior

I was a tachiyomi user,, just started using it after manually adding each manga. Shouldn't it have a feature on updating manga?

### Actual behavior

No library updating feature 

### Mangayomi version

0.1.61

### Device

Realme GT master edition 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by feelingwalnut** [comment]
second this.
there is an update in each manga in the library if you open them, at the top right on desktop application.
but nothing in the library itself for all mangas and nothing scheduled/automatic that ive seen.
