### ISSUE TITLE
Windows application download not working 

### ISSUE THREAD

**Issue by Tochage143** [kodjodevf/mangayomi#102]
### Steps to reproduce

I use extensions name aniwatch and it play the vedio . the vedio is working but when add to the download and than i check download there no download list .why 

### Expected behavior

anime should be download and also show in download screen list 

### Actual behavior

there is download in the download screen after add to the download 

### Mangayomi version

Mangayomi-v0.1.61-windows.exe

### Device

windows

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by kodjodevf** [comment]
Are you still having the same problem?

**Comment by MedoshiSenpai** [comment]
I also have this problem. It's just like aniyomi when it was newly released
