### ISSUE TITLE
Video 

### ISSUE THREAD

**Issue by Nimuthu2021** [kodjodevf/mangayomi#116]
### Steps to reproduce

1. Watch some thing 

### Expected behavior

The video should not lag and should be smooth 

### Actual behavior

The video lagges a lot, Its not Optimized to the video player

### Mangayomi version

0.0.67

### Device

Windows 11 

### Acknowledgements

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [ ] I have written a short but informative title.
- [ ] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [ ] I have updated all installed extensions.

**Comment by kodjodevf** [comment]
Can you please share a vidéo recording

**Comment by Daisy-Layard** [comment]
I have this problem too, and it may take a long time to load the beginning of videos

**Comment by Smiley1830** [comment]
That's probably a server problem, just switch between server(vidstreaming,vidcloud,MP4upload,etc.)
![Screenshot_20240202_121810](https://github.com/kodjodevf/mangayomi/assets/95736297/4bc0b5ae-a736-4655-a64a-47db003ec597)

**Comment by kodjodevf** [comment]
Fixed since [v0.1.65](https://github.com/kodjodevf/mangayomi/releases/tag/v0.1.65)
