### ISSUE TITLE
Bottom options bar in manga viewer glitched

### ISSUE THREAD

**Issue by IntelCorei5-8350u** [kodjodevf/mangayomi#119]
### Steps to reproduce

Read a manga

### Expected behavior

The options bar should be completely hidden

### Actual behavior

![IMG_0508](https://github.com/kodjodevf/mangayomi/assets/105188534/660fd0fa-54da-4438-9a1b-d7641cfe9f49)
You can see it glitched at the navbar

### Mangayomi version

0.1.65

### Device

iPad Mini 6, iPadOS 17

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by kodjodevf** [comment]
Ok will check it

**Comment by bolabola6789** [comment]
> Ok will check it
Bug is still there, even on v0.2.2 unfortunately
