### ISSUE TITLE
Download formats

### ISSUE THREAD

**Issue by Codingkingsman** [kodjodevf/mangayomi#125]
### Describe your suggested feature

The software is amazing compared to the previous ones that I've used
but I would like to have an option to download the manga as a ".pdf" or a ".cbz" format
this would make it easier for me to read the manga offline; rather than having so many images(for certain manga)
Thanks in advance!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.

**Comment by Delta18-Git** [comment]
Downloading as CBZ is possible in the settings.
