### ISSUE TITLE
[Windows/Mac/Linux] Allow right-click to have same function as long press

### ISSUE THREAD

**Issue by Delta18-Git** [kodjodevf/mangayomi#127]
### Describe your suggested feature

Currently the long-press action on computers is very cumbersome and annoying when you are trying to change a tag etc. for multiple manga/anime. If right-click is implemented, it would be much faster.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.

**Comment by Delta18-Git** [comment]
OK, so looked at the code with my *very very* basic Dart knowledge, and what I've understood it that the LongPressStateProvider and MangaLongPressStateProvider are only updated when a widget responds to the OnLongPress action, which ***only*** works with long-pressing. I don't really know if this request is feasible now.

**Comment by kodjodevf** [comment]
Added will be available in the next release
