### ISSUE TITLE
Manga showing a grey screen after update

### ISSUE THREAD

**Issue by Smiley1830** [kodjodevf/mangayomi#129]
### Steps to reproduce

1.Updated the app to 0.1.75
2. Updated my library
3. Click on one of my manga
4. A grey screen only shows

### Expected behavior

It should just led me to the chapters scree, but I am not able to do anything.

### Actual behavior

A grey screen shows 
![Screenshot_20240209_104948](https://github.com/kodjodevf/mangayomi/assets/95736297/f92a7e1c-80a0-4889-8dc7-3c1dbde86e5b)
![image](https://github.com/kodjodevf/mangayomi/assets/95736297/43774be7-b1e2-4db5-af1d-827d212ad2b9)

### Mangayomi version

0.1.75

### Device

Windows 11/Samsung S23+ (Android 14)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by Adminjojo** [comment]
I have the same kind of error but with an error written : 
![Screenshot_2024-02-10-00-49-07-176_com kodjodevf mangayomi](https://github.com/kodjodevf/mangayomi/assets/1921823/87d8753c-a89c-49dd-9020-f7986effee8e)

**Comment by kodjodevf** [comment]
Have you tried to do backup before update?

**Comment by Smiley1830** [comment]
In my case, it takes an old backup regardless if I made a new one, so I have to delete all backups in order for the new one to take affect, but that's a different issue. I tried reinstalling the app and I was able to access the manga again with an old backup, but once I refresh the library, it went back to Grey and can no longer access it, and it's only a few manga that I'm having this problem with.

**Comment by Adminjojo** [comment]
> Have you tried to do backup before update?

Its fixed, i had to update the mangas sources x)
