### ISSUE TITLE
Get to the Next Episode without clicking out

### ISSUE THREAD

**Issue by GodDraken** [kodjodevf/mangayomi#133]
### Describe your suggested feature

There should be a slider option in the current episode playing to switch to the next episode. It could look like the photo below.

### Other details

![image](https://github.com/kodjodevf/mangayomi/assets/153966766/8735fdb2-9060-41a2-8c54-9bc7dff0f74f)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.

**Comment by kodjodevf** [comment]
Added!
