### ISSUE TITLE
Search doesn't work when globally searching for manga

### ISSUE THREAD

**Issue by SumGui126** [kodjodevf/mangayomi#136]
### Steps to reproduce

Click search icon next to browse in manga sources

Search for anything

Shows error screen

### Expected behavior

Should search for manga in all available extensions you have available 

### Actual behavior

![Screenshot_20240216-205604](https://github.com/kodjodevf/mangayomi/assets/160294666/7bbb639a-b5f5-4897-abbb-d7bebf56d6eb)

### Mangayomi version

0.1.75

### Device

OnePlus Nord n10

### Other details

I tried uninstalling, deleting my settings, nothing works.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by kodjodevf** [comment]
It will be fixed in the next release, for now use individual search instead
