### ISSUE TITLE
Mangayomi starts up as a white screen when running the binary

### ISSUE THREAD

**Issue by infyProductions** [kodjodevf/mangayomi#137]
### Steps to reproduce

Simply run the binary using typing ./mangayomi in a terminal window
![shot-2024-02-19_20-10-57](https://github.com/kodjodevf/mangayomi/assets/31158494/871d4b69-99d9-420d-875a-f457192d103b)

### Expected behavior

Everything should be populated and not just a white screen

### Actual behavior

Upon launching said binary results in a white screen
![shot-2024-02-19_20-12-21](https://github.com/kodjodevf/mangayomi/assets/31158494/7361590f-b113-4129-a8fc-dc819fce43d0)

### Mangayomi version

0.1.75

### Device

Gentoo Linux (6.6.13-gentoo-dist, OpenRC), Enlightenment WM 0.25.4 (under X11)

### Other details

Before I reached at the current issue, I had to do the following (under Gentoo Linux):
1. Install missing dependencies upon launching the binary:
- `net-libs/webkit-gtk-2.42.4-r410` (has to be 4.x and not 6.x)
- `media-video/mpv `and `net-misc/yt-dlp` (probably required for the video playback portion)
2. Resolve the missing `libmpv.so.1` by performing a symlink to `libmpv.so.2`

Here's the output from the terminal app after launching the binary:

![shot-2024-02-19_20-19-31](https://github.com/kodjodevf/mangayomi/assets/31158494/0bb112e7-daee-4b7f-a4b3-f3b09d590f60)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by infyProductions** [comment]
I finally found the problem after a few searches. As it turns out, I'm running the app from a /home/(user) directory and it requires "xdg-user-dir" which is missing in my setup. Just installed `x11-misc/xdg-user-dirs` (and updated the version to 0.1.85) and it finally works once again.
![shot-2024-02-25_20-44-38](https://github.com/kodjodevf/mangayomi/assets/31158494/96172f88-1c1c-4b99-acb5-cfaafd568707)

**Comment by kodjodevf** [comment]
Glad to see it works

**Comment by infyProductions** [comment]
I'm going to be closing the issue since it's now resolved (unless there's a problem). Might add a "feature request" on what dependencies are required if running under Linux in the readme file.
