### ISSUE TITLE
The Appimage does not run on SteamOS 3.5

### ISSUE THREAD

**Issue by dtantono** [kodjodevf/mangayomi#138]
### Steps to reproduce

1. download the latest version (the current version v0.1.75)
2. run cd /home/deck/Downloads/ on the terminal
3. run ./Mangayomi-v0.1.75-linux.appimage
4. I got error message  ./Mangayomi-v0.1.75-linux.appimage: error while loading shared libraries: libmpv.so.1: cannot open shared object file: No such file or directory

### Expected behavior

it should run 

### Actual behavior

it does not run at all

![Screenshot_20240220_212244](https://github.com/kodjodevf/mangayomi/assets/29157187/e5b9939e-28e9-4f06-93bb-1fbf53d41986)

### Mangayomi version

0.1.75

### Device

Steam Deck

### Other details

Since SteamOS is an immutable OS and every custom package installation via pacman will gone after OS update. I suppose you should bundle webkit2gtk-4.1 directly on the Appimage directly instead. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by kodjodevf** [comment]
Try ` sudo apt-get install webkit2gtk-4.1 clang cmake ninja-build pkg-config libgtk-3-dev mpv libmpv-dev dpkg-dev`

**Comment by dtantono** [comment]
As I said before, SteamOS is based on Arch Linux which is based on pacman. So, it is possible with sudo pacman -S webkit2gtk-4.1 clang cmake ninja pkg-config gtk3 base-devel  mpv which is equivalent with the debian based distro sudo apt-get install webkit2gtk-4.1 clang cmake ninja-build pkg-config libgtk-3-dev mpv libmpv-dev dpkg-dev. But, the thing is each OS update every custom pacman package installation will be gone (same like ChromeOS), and it is not feasible to run the same command again to run the app again on the terminal after OS update. Is it possible to bundled it on the Appimage instead?

**Comment by kodjodevf** [comment]
I will say that it is not feasible given the size of the bundle, all I could do now is to remove webkit2gtk for the moment while waiting for a better solution or do you have a solution to propose?

**Comment by dtantono** [comment]
maybe you can try flatpak packaging https://github.com/flatpak/flatpak

**Comment by kodjodevf** [comment]
Ok will check, for now Can you try this[#86]

**Comment by dtantono** [comment]
it looks like separate package called mpv needs to be installed manually via pacman and again since, SteamOS is immutable distro. if we installed the package manually. it will be gone in the next system update
![Screenshot_20231221_105403](https://github.com/kodjodevf/mangayomi/assets/29157187/1eacd8bc-ea30-4a15-a933-1eed32b083a2)

**Comment by kodjodevf** [comment]
Since this appears to be fixed, I'm closing this

**Comment by BloodVaine** [comment]
has there been a solution to get it working on steamdeck?
