### ISSUE TITLE
Animes I search doesn't have any images on MacOS M1

### ISSUE THREAD

**Issue by iFloneUEFN** [kodjodevf/mangayomi#139]
### Steps to reproduce

- Downloaded the app from github for macOS.
- Launched the app
- Browser section
- Typing anything such as test

### Expected behavior

Showing anime images aka covers from the searching if available

### Actual behavior

Not showing any anime cover + displaying the following error:

<img width="798" alt="image" src="https://github.com/kodjodevf/mangayomi/assets/83962218/e5009063-ce10-4a59-8e0f-84393db68ba1">

### Mangayomi version

0.1.75

### Device

MacBook Pro M1 - Sonoma 14.3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by kodjodevf** [comment]
It will be fixed in the next release, for now use individual search instead
