### ISSUE TITLE
Manga sources return: Exception: type 'SMSource' is not a subtype of type 'MProvider' in type cast

### ISSUE THREAD

**Issue by Eltovarish** [kodjodevf/mangayomi#142]
### Steps to reproduce

-Install last update
-Try turning off all English sources (to only have the ones on Spanish, my native language)
-search for a manga or click on any source from your sources list
-the error appears

-I turn every source 'ON' again
-The error is still here :c

### Expected behavior

I get to read manga to escape from my miserable life.

### Actual behavior

I get: 
Exception: type 'SMSource' is not a subtype of type 'MProvider' in type cast

And no manga :c
![Screenshot_2024-02-24-22-51-59-080_com kodjodevf mangayomi](https://github.com/kodjodevf/mangayomi/assets/161176922/89777575-2f49-4fd2-b3c6-289a716a57c8)
![Screenshot_2024-02-24-22-52-03-484_com kodjodevf mangayomi](https://github.com/kodjodevf/mangayomi/assets/161176922/ca70674f-298e-4360-bdad-489940798509)

### Mangayomi version

0.1.85

### Device

Xiaomi Redmi Note 11S / MIUI 14.0.6 /Android 13? I'm not sure

### Other details

I had a lot of things to add here but I forgot while creating the account and searching for the things that the template asks me, I'm seriously sorry :c

I love this program so I hope this is something that happens to me, or something easy to fix ^^

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by kodjodevf** [comment]
You have to update all sources to the latest version
