### ISSUE TITLE
Unable to watch some series on MacBook Pro M1

### ISSUE THREAD

**Issue by Florian-Martinez** [kodjodevf/mangayomi#145]
### Steps to reproduce

1. Downloading the newest version.
2. Launching the app.
3. Searching for my series or clicking on random ones

### Expected behavior

Play the content.

### Actual behavior

Getting this nice window:

<img width="794" alt="image" src="https://github.com/kodjodevf/mangayomi/assets/83962218/32e388cb-67ea-4180-b162-37b50d9d6332">

### Mangayomi version

0.1.8.5

### Device

MacBook Pro M1 Sonoma 14.3.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by kodjodevf** [comment]
This concerns the sources not the application itself, if you want to report issues concerning a source use this [link](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose)
