### ISSUE TITLE
Is there a way to insert a source? Alternatively, could you introduce the Mangaworld source into the application?

### ISSUE THREAD

**Issue by Alfrichx** [kodjodevf/mangayomi#147]
### Describe your suggested feature

I downloaded the app on an iPhone 13 Pro running iOS 17.4. I am Italian, and the basic sources are limited, with 2 out of 3 not functioning. Therefore, I was wondering if it’s possible to add additional sources to the app or if you could introduce them in the next update.

https://www.mangaworld.ac/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.

**Comment by kodjodevf** [comment]
Use this [link](https://github.com/kodjodevf/mangayomi-extensions) in the contribution section to find out how to add your own source.
