### ISSUE TITLE
how to run

### ISSUE THREAD

**Issue by witchfindertr** [kodjodevf/mangayomi#15]
E/flutter ( 1435): #0      nCall (package:isar/src/native/isar_core.dart:174:5)
E/flutter ( 1435): #1      openIsarSync.<anonymous closure> (package:isar/src/native/open.dart:141:5)
E/flutter ( 1435): #2      using (package:ffi/src/arena.dart:124:31)
E/flutter ( 1435): #3      openIsarSync (package:isar/src/native/open.dart:129:10)
E/flutter ( 1435): #4      Isar.openSync (package:isar/src/isar.dart:137:12)
E/flutter ( 1435): #5      StorageProvider.initDB (package:mangayomi/providers/storage_provider.dart:101:23)
E/flutter ( 1435): <asynchronous suspension>
E/flutter ( 1435): #6      main (package:mangayomi/main.dart:40:10)
E/flutter ( 1435): <asynchronous suspension>
E/flutter ( 1435): 
I/flutter ( 1435): ╔══════════════════════════════════════════════════════╗
I/flutter ( 1435): ║                 ISAR CONNECT STARTED                 ║
I/flutter ( 1435): ╟──────────────────────────────────────────────────────╢
I/flutter ( 1435): ║         Open the link to connect to the Isar         ║
I/flutter ( 1435): ║        Inspector while this build is running.        ║
I/flutter ( 1435): ╟──────────────────────────────────────────────────────╢
I/flutter ( 1435): ║ https://inspect.isar.dev/3.1.0+1/#/51535/o57r2VWbq8s ║
I/flutter ( 1435): ╚══════════════════════════════════════════════════════╝

**Comment by witchfindertr** [comment]
emulator problem fixed x64

**Comment by kodjodevf** [comment]
Can you describe the problem you encountered
