### ISSUE TITLE
Has problems with servers 

### ISSUE THREAD

**Issue by Nimuthu2021** [kodjodevf/mangayomi#151]
### Steps to reproduce

1. Try to watch something

### Expected behavior

It should play the video 

### Actual behavior

It has server errors 

### Mangayomi version

0.1.85

### Device

iPhone X

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by kodjodevf** [comment]
What source ?

**Comment by Nimuthu2021** [comment]
Basically every source
