### ISSUE TITLE
Why there a suspicious contact IP when i scan this app?

### ISSUE THREAD

**Issue by Allphonso** [kodjodevf/mangayomi#153]
### Steps to reproduce

https://www.virustotal.com/gui/file/9b6c1f3d67ec12a6ec219d1647a5ada67f3ff6ee7a9249e08af98917eb821287/relations

### Expected behavior

Can you explain it

### Actual behavior

Or someone explain it 

### Mangayomi version

V0.2.0

### Device

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by StShAzzy** [comment]
suspicious IPs don't mean much...
they could be merely flagged as malicious for simply not complying with anti-piracy laws
