### ISSUE TITLE
Failure to launch on iOS 12 (possible misconfigured supported iOS version)

### ISSUE THREAD

**Issue by ZedZagg** [kodjodevf/mangayomi#154]
### Steps to reproduce

1. Download the .ipa from the github releases
2. Install via Sideloadly (Using either Apple ID sideload or Ad-hoc sign) on Windows 10
3. Open the app on the iPad

### Expected behavior

Application opens and reaches a start page.

### Actual behavior

A white screen opens for a fraction of a second before closing and the system returning to the home screen.

### Mangayomi version

0.2.0, 0.1.85

### Device

iPad mini 2, iOS 12.5.7 (chimera jailbreak)

### Other details

There seems to be contradictions in what iOS versions are compatible, if I am reading this information right:
- The apple .ipa file in the releases has the minimum compatible OS version set to 12.0, allowing it to be installed on those devices.
- mangayomi/ios/Podfile seems to list iOS 13 as the minimum on line 2: `platform :ios, '13.0'`
- former issues also imply that 13 is the minimum [here](https://github.com/kodjodevf/mangayomi/issues/32#issuecomment-1749821456)

I note that others have had luck installing [using sideloadly](https://github.com/kodjodevf/mangayomi/issues/144). I can install other apps with sideloadly and confirm they work. I tested multiple versions with Apple ID signing and ad-hoc signing and haven't noticed a difference.

I honestly fully expect the app was never intended to run on this OS and for some reason is able to be installed when it shouldn't.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [ ] I have updated all installed extensions.

**Comment by kodjodevf** [comment]
iOS 13 is the minimum compatible OS version
