### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by Yursd** [kodjodevf/mangayomi#156]
### Describe your suggested feature

1. Set the User-Agent for webview
   >for websites with different UI for mobile and desktop, if data scraping is targeted at desktop pages, after opening a webview on Android, data scraping may not work).
3. Adapt horizontal images
   >currently, the extension's interface is only suitable for displaying vertical images, and the display of horizontal images is not optimal).

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.

**Comment by kodjodevf** [comment]
Added horizontal continue in the lastest release
