### ISSUE TITLE
The window state cannot be saved

### ISSUE THREAD

**Issue by abrclano** [kodjodevf/mangayomi#157]
### Steps to reproduce

1.Change the window size and position of the mangayomi
2.Turn mangayomi off and back on
3.Observe the state of the mangayomi window

### Expected behavior

The position and size of the window should be the state after I changed it

### Actual behavior

The window position and size return to the default state

### Mangayomi version

v0.2.2

### Device

Windows 11 22631.3296

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by ryanwuson** [comment]
This also happens with the mac
