### ISSUE TITLE
Suggestion: windows software enhancement

### ISSUE THREAD

**Issue by knightmob** [kodjodevf/mangayomi#16]
Pls add this crucial parts.
- preload pages
- scale type
![Screenshot_2023_0808_223126.png](https://github.com/kodjodevf/mangayomi/assets/76065610/7a05a601-e66f-440a-896d-b8e38c3302e5)

![Screenshot_2023_0808_223022.png](https://github.com/kodjodevf/mangayomi/assets/76065610/0bbd8251-2ddf-4e12-8067-2339502a36a3)

Especially Scale type, since the default display of mangayomi is too big, I prefer it follow a default format size then add scale type for users preference.

Also I forgot, there seems to be issue in your extension layout, I can't delete it after I download it, I can only hide it, but I want to delete, anyways great update! keep up the good work!

**Comment by kodjodevf** [comment]
I just published a new release, I will fix it in a next version

**Comment by knightmob** [comment]
> I just published a new release, I will fix it in a next version

all good for me, thanks for noticing!

**Comment by kodjodevf** [comment]
These features have been added, you can check in the latest release
