### ISSUE TITLE
The client post method is not sending request   

### ISSUE THREAD

**Issue by Ejobat** [kodjodevf/mangayomi#170]
This HTML snippet is taken from a website. It demonstrates how a search request is structured:

```html
<div id="nav-search">
    <form action="https://www.thenollyverse.com/search.php" method="POST">
        <input required="" autocomplete="off" class="input" id="name" name="name" placeholder="Search movies &amp; series..." /><span id="result" class="help-block"></span>
    </form>
    <button class="nav-close search-close"><span></span></button>
</div>
```

I attempted to write a search function, but it doesn't send the query as expected. Here's the JavaScript code I wrote:

```javascript
async search(query, page, filters) {
    const url = "https://www.thenollyverse.com/search.php";
    const data = {
        name: "mydemon" // The search query
    };
    const headers = {
        "Content-Type": "application/x-www-form-urlencoded",
    };
    const res = await new Client().post(url, headers, data);
    console.log(res.body);
}
```

When I search directly in the browser, the response looks like this:

```html
<link rel="canonical" href="https://www.thenollyverse.com/search/mydemon">
```

However, when I send the request from my function, the response looks like this:

```html
<link rel="canonical" href="https://www.thenollyverse.com/search/">
```

It seems the query is not being sent. How can I fix this issue?

**Comment by kodjodevf** [comment]
On which platform did you test the code?

**Comment by DarkLite25** [comment]
The same problem I have found in the Android app

**Comment by kodjodevf** [comment]
> This HTML snippet is taken from a website. It demonstrates how a search request is structured:
> 
> ```
> <div id="nav-search">
>     <form action="https://www.thenollyverse.com/search.php" method="POST">
>         <input required="" autocomplete="off" class="input" id="name" name="name" placeholder="Search movies &amp; series..." /><span id="result" class="help-block"></span>
>     </form>
>     <button class="nav-close search-close"><span></span></button>
> </div>
> ```
> 
> I attempted to write a search function, but it doesn't send the query as expected. Here's the JavaScript code I wrote:
> 
> ```js
> async search(query, page, filters) {
>     const url = "https://www.thenollyverse.com/search.php";
>     const data = {
>         name: "mydemon" // The search query
>     };
>     const headers = {
>         "Content-Type": "application/x-www-form-urlencoded",
>     };
>     const res = await new Client().post(url, headers, data);
>     console.log(res.body);
> }
> ```
> 
> When I search directly in the browser, the response looks like this:
> 
> ```
> <link rel="canonical" href="https://www.thenollyverse.com/search/mydemon">
> ```
> 
> However, when I send the request from my function, the response looks like this:
> 
> ```
> <link rel="canonical" href="https://www.thenollyverse.com/search/">
> ```
> 
> It seems the query is not being sent. How can I fix this issue?

Try this code ```
const data = {
        'name': query
      };
      const res = await new Client().post(`${baseUrl}/livesearch.php`, {}, data);
```
