### ISSUE TITLE
Add a button to delete all cookies

### ISSUE THREAD

**Issue by Ftbom** [kodjodevf/mangayomi#174]
### Describe your suggested feature

After opening a webview, the headers setting of Client.get() may change, which sometimes can cause the extension to not work. A button to reset the headers can be added on the extension detail page.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.

**Comment by kodjodevf** [comment]
Can you give some uses cases

**Comment by Ftbom** [comment]
https://github.com/kodjodevf/mangayomi-extensions/blob/main/javascript%2Fmanga%2Fsrc%2Fzh%2Fcopymanga.js#L182-L184

In the above code, the User-Agent for a desktop environment is set through headers. However, if a webview is opened on an Android platform later, the User-Agent will be overwritten to be mobile.

**Comment by kodjodevf** [comment]
Oh I see. I will see what to do for this

**Comment by kodjodevf** [comment]
Fixed!
