### ISSUE TITLE
Download Glitch

### ISSUE THREAD

**Issue by MrexXtra419** [kodjodevf/mangayomi#176]
### Steps to reproduce

click on download but it doesnt download

### Expected behavior

it suppose to download the chapter clicked on

### Actual behavior

doesnt download

### Mangayomi version

0.2.4

### Device

kali linux

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by feelingwalnut** [comment]
same issue, shell output on linux is:
'/home/nix/Applications/Mangayomi-v0.2.4-linux.AppImage' 
package:media_kit_libs_linux registered.
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LateInitializationError: Field '_storage@1813152722' has already been initialized.
#0      LateError._throwFieldAlreadyInitialized (dart:_internal-patch/internal_patch.dart:184)
#1      BaseDownloader._storage= (package:mangayomi/services/background_downloader/src/base_downloader.dart:47)
#2      new BaseDownloader.instance (package:mangayomi/services/background_downloader/src/base_downloader.dart:107)
#3      new FileDownloader._internal (package:mangayomi/services/background_downloader/src/file_downloader.dart:45)
#4      new FileDownloader (package:mangayomi/services/background_downloader/src/file_downloader.dart:39)
#5      downloadChapter (package:mangayomi/modules/manga/download/providers/download_provider.dart:237)
<asynchronous suspension>
#6      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

**Comment by kodjodevf** [comment]
Fixed!
