### ISSUE TITLE
screen goes blank on scroll (linux)

### ISSUE THREAD

**Issue by apurvsikka** [kodjodevf/mangayomi#183]
### Steps to reproduce

1. go to any tab 
2. scroll/ move the mouse a bit
3. screen turns blank

### Expected behavior

the sources should be cycled through

### Actual behavior

the screen turns blank

### Mangayomi version

0.2.45

### Device

hp laptop (idk the model) , running arch linux (latest)

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [x] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by kodjodevf** [comment]
Can you send screenshots?

**Comment by apurvsikka** [comment]
![image](https://github.com/kodjodevf/mangayomi/assets/102051299/1e926359-e077-4d6e-b09e-2a7c418f1f7a)

**Comment by apurvsikka** [comment]
Update: tried using the prebuilt binaries and  appimage too, it is also giving same results (i built it from the source before)

**Comment by apurvsikka** [comment]
[rec1o.webm](https://github.com/kodjodevf/mangayomi/assets/102051299/eb8df622-afb7-4a85-ae48-7e1d0c5c539c)

**Comment by apurvsikka** [comment]
update: tried downgrading and it works on 0.2.4 , gess i gotta stick to that till a new release comes out

**Comment by t9999clint** [comment]
I have the same issue.
Fedora 40 (Bazzite)
Also on Ubuntu and Arch.
This is on my AMD system with a Rx 6750
Also with my Intel Laptop with HD graphics (also on fedora).
This sometimes affects other sections of the app, but 99% of the time it's the browsing section that causes it.

**Comment by Delta18-Git** [comment]
This is happening on my Arch install (Wayland) but not just on scroll, but on launching the app. If different from this issue, I'll create a new issue when I boot into Arch.

**Comment by kodjodevf** [comment]
It seem to be fixed
