### ISSUE TITLE
To add Toonstream extension for Hindi dubbed anime

### ISSUE THREAD

**Issue by Mushibull21** [kodjodevf/mangayomi#187]
### Describe your suggested feature

It have lot of dubbed anime with 1080p quantity and good loading time and timely updated.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.

**Comment by Mushibull21** [comment]
Please add this extension for Hindi dubbed anime.

**Comment by apurvsikka** [comment]
please open an issue in the [extensions](https://github.com/kodjodevf/mangayomi-extensions/) repo regarding this
