### ISSUE TITLE
Bottom tabs too high on home button devices

### ISSUE THREAD

**Issue by ProvokedGamer** [kodjodevf/mangayomi#19]
iOS 15.6
iPhone 8+

Issue: The bottom tabs are placed too high on home button devices (probably because that space is meant for the homebar on non-home-button iPhone devices). 

It looks a little weird for it to be so high on home button devices.

![image](https://github.com/kodjodevf/mangayomi/assets/119907145/a801d1c4-934e-40e7-a6cb-9b2652d004d4)

**Comment by kodjodevf** [comment]
Oh I see, I'll fix it

**Comment by ProvokedGamer** [comment]
Thanks!

**Comment by kodjodevf** [comment]
Done! you can check in the latest release

**Comment by ProvokedGamer** [comment]
Thanks!
