### ISSUE TITLE
App image doesn't start on Gentoo - MPV dependency not included as part of AppImage.

### ISSUE THREAD

**Issue by arran4** [kodjodevf/mangayomi#190]
### Steps to reproduce

```
arran@arran-desktop:/home/arran/Downloads 19422 
% chmod +x Mangayomi-v0.2.55-linux.AppImage 
arran@arran-desktop:/home/arran/Downloads 19423 
% ./Mangayomi-v0.2.55-linux.AppImage 
./Mangayomi-v0.2.55-linux.AppImage: error while loading shared libraries: libmpv.so.1: cannot open shared object file: No such file or directory
```

### Expected behavior

It should open

### Actual behavior

```
./Mangayomi-v0.2.55-linux.AppImage: error while loading shared libraries: libmpv.so.1: cannot open shared object file: No such file or directory
```

### Mangayomi version

v0.2.55

### Device

Gentoo Linux Desktop

### Other details

I do however have it installed.

![image](https://github.com/kodjodevf/mangayomi/assets/111667/f4364e3f-9d21-4472-a7dd-266ec0192524)

However the so version is different:

![image](https://github.com/kodjodevf/mangayomi/assets/111667/3b406cae-92a4-421b-b6f0-778e8f7f9a58)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by Ebraama06** [comment]
I have  the same problem and command output "failed to create symbolic link '/usr/lib/x86_64-linux-gnu/libmpv.so.1': No such file or directory".
did anyone solve it?
I use arch Linux

**Comment by Ebraama06** [comment]
i just fix it with this command  `sudo ln -sf /usr/lib/libmpv.so /usr/lib/libmpv.so.1`

**Comment by arran4** [comment]
I did solve it that way too, but it's not a proper "solution" as it require modifying the base system's /usr without the use of a package to do so. (Which shows up on integrity checks.)

**Comment by arran4** [comment]
As far as I can tell it tries to dynamically load the correct libraries:
```
      'linux': [
        'libmpv.so',
        'libmpv.so.2',
        'libmpv.so.1',
      ],
```

https://github.com/media-kit/media-kit/blob/ff00dae2b9bb6e66cdf15a7ecc1f99d0b7d6e3b4/media_kit/lib/src/player/native/core/native_library.dart#L53-L57

**Comment by arran4** [comment]
It looks like that this will "resolve itself" when github actions `ubuntu-latest` migrates from 22.04 LTS to 24.04 LTS:

![image](https://github.com/kodjodevf/mangayomi/assets/111667/cb947c19-cb35-451d-8723-adec4b58f229)

How do I know this? Well the images are built with `ubuntu-latest` in github actions here:

https://github.com/kodjodevf/mangayomi/blob/e4632395bac7a95d3353b5d6cdcdfae3d6d670d3/.github/workflows/release.yml#L260

So it doesn't really warrant much investigation for our issues we just have to wait. However the problem will crop up every time ubuntu decides to create a new major version of mpv. 

The build pulls in `libmpv-dev`

https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=libmpv&searchon=names

It's build on jammy, so we look at Jammy's versions:

![image](https://github.com/kodjodevf/mangayomi/assets/111667/4a088d9b-b0b4-4b17-bd3e-009e631196d1)

https://packages.ubuntu.com/jammy/libmpv-dev

There is no libmpv2 for jammy.So we look at libmpv1 for jammy:

https://packages.ubuntu.com/jammy/libmpv1

Then it's file list:

https://packages.ubuntu.com/jammy/amd64/libmpv1/filelist

![image](https://github.com/kodjodevf/mangayomi/assets/111667/0b25b684-aa95-4c26-88f9-53b1d875e067)

Although what's odd is that `libmpv-dev` for jammy is installing the plain `.so` too:

![image](https://github.com/kodjodevf/mangayomi/assets/111667/ca8eb977-05be-4587-aa9e-791272a6d8ad)

So I don't know what's with the preference. (edit, it's `ld`)

Although `libmpv2` isn't available on Jammy yet:

![image](https://github.com/kodjodevf/mangayomi/assets/111667/303b981d-fbe8-497a-95e2-ac61f8bd4263)

The install line is:
```
          sudo apt-get install webkit2gtk-4.1 clang cmake ninja-build pkg-config libgtk-3-dev mpv libmpv-dev dpkg-dev
```

Which should install those files.

According to docker it does:
```
root@9b6f2b225d33:/usr/lib/x86_64-linux-gnu# ls -l libmpv*
lrwxrwxrwx 1 root root      17 Feb  6  2022 libmpv.so -> libmpv.so.1.109.0
lrwxrwxrwx 1 root root      17 Feb  6  2022 libmpv.so.1 -> libmpv.so.1.109.0
-rw-r--r-- 1 root root 2503552 Feb  6  2022 libmpv.so.1.109.0
root@9b6f2b225d33:/usr/lib/x86_64-linux-gnu# uname -a
Linux 9b6f2b225d33 6.6.30-gentoo-x86_64 #1 SMP PREEMPT_DYNAMIC Sun May 19 17:08:34 AEST 2024 x86_64 x86_64 x86_64 GNU/Linux
root@9b6f2b225d33:/usr/lib/x86_64-linux-gnu# cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
root@9b6f2b225d33:/usr/lib/x86_64-linux-gnu# apt-get install webkit2gtk-4.1 clang cmake ninja-build pkg-config libgtk-3-dev mpv libmpv-dev dpkg-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'libwebkit2gtk-4.1-dev' for regex 'webkit2gtk-4.1'
Note, selecting 'libwebkit2gtk-4.1-0' for regex 'webkit2gtk-4.1'
pkg-config is already the newest version (0.29.2-1ubuntu3).
clang is already the newest version (1:14.0-55~exp2).
libmpv-dev is already the newest version (0.34.1-1ubuntu3).
mpv is already the newest version (0.34.1-1ubuntu3).
ninja-build is already the newest version (1.10.1-1).
cmake is already the newest version (3.22.1-1ubuntu1.22.04.2).
dpkg-dev is already the newest version (1.21.1ubuntu2.3).
libgtk-3-dev is already the newest version (3.24.33-1ubuntu2.1).
libwebkit2gtk-4.1-0 is already the newest version (2.44.2-0ubuntu0.22.04.1).
libwebkit2gtk-4.1-dev is already the newest version (2.44.2-0ubuntu0.22.04.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

IDK why it's preferring the `.1` version. If it was simply following the symlink it would be `libmpv.so.1.109.0` and given the order (if that accounts for anything):

```
      'linux': [
        'libmpv.so',
        'libmpv.so.2',
        'libmpv.so.1',
      ],
```

It resolves it in that order:
```
      for (final name in names) {
        try {
          DynamicLibrary.open(name);
          _resolved = name;
          return;
        } catch (_) {}
      }
```

```
% ./Mangayomi-v0.2.6-linux.AppImage --appimage-extract
```

It's a bit more than a dynamic library: So two strikes against mediakit as being the culprit. 

```
arran@arran-desktop:/home/arran/Downloads/mangayomi/squashfs-root 21542 
% ldd AppRun | grep -i mpv
        libmpv.so.1 => not found

```

So it might not be a result of mediakit but something else. (The cmakes also seem fairly clean from a linux perspective.

None of the other libraries seem to have a dependency on it (although the media kit repo is pulled in 3 times!)
```

```

A bit more digging, it seems to be an `ld` linking preference with the `pkg-config` output:
```
root@9b6f2b225d33:/usr/lib/x86_64-linux-gnu# cat /usr/lib/x86_64-linux-gnu/pkgconfig/mpv.pc
prefix=/usr
exec_prefix=/usr
libdir=/usr/lib/x86_64-linux-gnu
includedir=/usr/include

Name: mpv
Description: mpv media player client library
Version: 1.109.0
Requires:
Libs: -L${libdir} -lmpv
Libs.private: -lasound -lcaca -lcdio_paranoia -lcdio_cdda -lcdio -ldrm -ldvdnav -ldvdread -lEGL -lavutil -lavcodec -lavformat -lswscale -lavfilter -lswresample -lgbm -lwayland-egl -ljack -lpthread -lmujs -ljpeg -llcms2 -larchive -lass -lavdevice -lbluray -lm -lplacebo -lrt -llua5.2 -lpulse -lrubberband -lsamplerate -lSDL2 -lsixel -lspirv-cross-c-shared -luchardet -lva-drm -lva-wayland -lva-x11 -lva -lvdpau -lvulkan -lwayland-client -lwayland-cursor -lxkbcommon -lX11 -lXss -lXext -lXinerama -lXrandr -lXv -lzimg -lz
Cflags: -I${includedir}
```

Going to try modify the `-lmpv` to `-lmpv.so` in https://github.com/arran4/mangayomi/tree/v0.2.50003

Okay that failed, among a couple other things as the problem isn't in the mangayomi executable but the libmedia_kit_video one.

```
arran@arran-desktop:/home/arran/Downloads/mangayomi2/squashfs-root 21619 
% patchelf --print-needed AppRun           
libflutter_qjs_plugin.so
libisar_flutter_libs_plugin.so
libmedia_kit_libs_linux_plugin.so
libmedia_kit_video_plugin.so
libscreen_retriever_plugin.so
liburl_launcher_linux_plugin.so
libwindow_manager_plugin.so
libwindow_to_front_plugin.so
libflutter_linux_gtk.so
libgtk-3.so.0
libgdk-3.so.0
libpangocairo-1.0.so.0
libpango-1.0.so.0
libharfbuzz.so.0
libatk-1.0.so.0
libcairo-gobject.so.2
libcairo.so.2
libgdk_pixbuf-2.0.so.0
libgio-2.0.so.0
libgobject-2.0.so.0
libglib-2.0.so.0
libstdc++.so.6
libm.so.6
libgcc_s.so.1
libc.so.6
```

^ No MPV

However:

```
% patchelf --print-needed libmedia_kit_video_plugin.so     
libflutter_linux_gtk.so
libgtk-3.so.0
libgdk-3.so.0
libpangocairo-1.0.so.0
libpango-1.0.so.0
libharfbuzz.so.0
libatk-1.0.so.0
libcairo-gobject.so.2
libcairo.so.2
libgdk_pixbuf-2.0.so.0
libgio-2.0.so.0
libgobject-2.0.so.0
libglib-2.0.so.0
libmpv.so.1
libepoxy.so.0
libstdc++.so.6
libm.so.6
libgcc_s.so.1
libc.so.6
```

^ It is there.

Which is pulled in via: https://pub.dev/packages/media_kit_libs_linux/versions (if you download the source you can see that it's just source no binary so it's compiled locally.)

So adding this to the build (release.yml just before `mv build/linux/x64/release/bundle/{mangayomi,AppRun}`):

```
          patchelf --replace-needed libmpv.so.1 libmpv.so build/linux/x64/release/bundle/lib/libmedia_kit_video_plugin.so
          patchelf --replace-needed libmpv.so.1 libmpv.so build/linux/x64/release/bundle/lib/libmedia_kit_native_event_loop.so
```

That or you could potentially just include libmpv.so.1 in it but that is probably not a good idea:
```
root@9b6f2b225d33:/usr/lib/x86_64-linux-gnu# patchelf --print-needed libmpv.so.1
libasound.so.2
libcaca.so.0
libcdio_paranoia.so.2
libcdio_cdda.so.2
libcdio.so.19
libm.so.6
libdrm.so.2
libdvdnav.so.4
libEGL.so.1
libavutil.so.56
libavcodec.so.58
libavformat.so.58
libswscale.so.5
libavfilter.so.7
libswresample.so.3
libgbm.so.1
libwayland-egl.so.1
libwayland-client.so.0
libjack.so.0
libmujs.so.1
libjpeg.so.8
liblcms2.so.2
libarchive.so.13
libass.so.9
libavdevice.so.58
libbluray.so.2
libplacebo.so.192
liblua5.2.so.0
libpulse.so.0
librubberband.so.2
libSDL2-2.0.so.0
libsixel.so.1
libuchardet.so.0
libva.so.2
libva-drm.so.2
libva-wayland.so.2
libva-x11.so.2
libvdpau.so.1
libvulkan.so.1
libwayland-cursor.so.0
libxkbcommon.so.0
libX11.so.6
libXss.so.1
libXext.so.6
libXinerama.so.1
libXrandr.so.2
libXv.so.1
libzimg.so.2
libz.so.1
libc.so.6
```

:heavy_check_mark: :heavy_check_mark: :heavy_check_mark: :heavy_check_mark: :heavy_check_mark: 

That worked.

Proof:

https://github.com/arran4/mangayomi/releases/tag/v0.2.50007

Effective change:

https://github.com/arran4/mangayomi/blob/v0.2.5/.github/workflows/release.yml#L56-L58

Ignore all other changes.

This should continue to work for ubuntu as I verified as the `.so` links to the `.so.1` as it does to `.so.2` in Gentoo.

This means that there isn't a major API difference between the two versions, otherwise https://github.com/kodjodevf/mangayomi/issues/168 's  workaround would have never have worked.

**Comment by arran4** [comment]
```
arran@arran-desktop:/home/arran/Downloads 21704 
% chmod +x Mangayomi-v0.2.50009-linux.AppImage 
arran@arran-desktop:/home/arran/Downloads 21705 
% ./Mangayomi-v0.2.50009-linux.AppImage 

** (Mangayomi-v0.2.50009-linux.AppImage:58008): CRITICAL **: 15:34:55.452: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (Mangayomi-v0.2.50009-linux.AppImage:58008): CRITICAL **: 15:34:55.453: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (Mangayomi-v0.2.50009-linux.AppImage:58008): CRITICAL **: 15:34:55.453: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (Mangayomi-v0.2.50009-linux.AppImage:58008): CRITICAL **: 15:34:55.454: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (Mangayomi-v0.2.50009-linux.AppImage:58008): CRITICAL **: 15:34:55.454: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found
package:media_kit_libs_linux registered.
^C
arran@arran-desktop:/home/arran/Downloads 21706 
% cat /etc/os-release 
NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
VERSION_ID="2.15"
```
