### ISSUE TITLE
Not able to download anime

### ISSUE THREAD

**Issue by Mohul-Gaikwad** [kodjodevf/mangayomi#192]
### Steps to reproduce

1. Open mangayomi app
2. go to anime (ex. one piece)
3. click on download 
4. (does nothing besides loading and error)

### Expected behavior

Whenever I click n download button the app should download content (specifically talking about anime's)

### Actual behavior

it doesn't download and keeps on loading and gives error (something like this -- ClientException: A server with the specified hostname could not be found., uri=https://anitaku.to/kimetsu-no-yaiba-episode-1
<img width="1552" alt="Screenshot 2024-06-03 at 4 52 01 PM" src="https://github.com/kodjodevf/mangayomi/assets/122723964/e61be80e-4ea9-4b60-a475-b4c5dcc16f14">
)

### Mangayomi version

0.2.55

### Device

MacBook Pro M1 

### Other details

<img width="1552" alt="Screenshot 2024-06-03 at 4 52 01 PM" src="https://github.com/kodjodevf/mangayomi/assets/122723964/4685f30c-8337-41fd-a0b9-a2cc2779fe7b">

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by kodjodevf** [comment]
It depends on the servers, for some you can download and others not.

**Comment by MrD005** [comment]
@kodjodevf can you tell which server or extension supports anime download
