### ISSUE TITLE
download not working on some devices

### ISSUE THREAD

**Issue by Seyien** [kodjodevf/mangayomi#200]
### Steps to reproduce

1- I click on the download icon of the chapter box.
2- download icon constantly stays in download process

![screenshot](https://github.com/kodjodevf/mangayomi/assets/110932038/08394d5c-bb32-41aa-a315-a8bae8a0efe0)

### Expected behavior

when I click on the download icon it should download.

### Actual behavior

download icon constantly stays in download process

### Mangayomi version

0.2.45

### Device

alcatel 8068 android 8.1.0

### Other details

I wanted to try the download feature on my old tablet and ran into this problem.

I think on some older devices the download function does not work.

I should also mention that when downloading, the download queue is empty.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by mumiby** [comment]
Same issue. It didn't crash the first time I tried to download 100+ chapters. Then it crashed in the background and from that time onward it crashes every single time. For unfinished downloads, I didn't see any Resume/Pause option in the download screen so I just go back to the chapters screen and select Download unread again. It still crashes.

**Comment by JoeShymoe** [comment]
Same issue.
