### ISSUE TITLE
"Mangayomi" is no longer available

### ISSUE THREAD

**Issue by bobabear1** [kodjodevf/mangayomi#201]
### Steps to reproduce

I tried to open the app as usual by clicking on it but I kept getting the same error.

### Expected behavior

It should open as it does normally however it keeps saying it's no longer available.

### Actual behavior

The app keeps uninstalling for some reason every few days/weeks. I have to redownload it so it works again. Everything inside the app is fine but it keeps getting removed.

### Mangayomi version

0.2.45

### Device

Iphone Xr and IOS 17.5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by kelanatr** [comment]
This isn’t an issue with the app, it’s a restriction with sideloading. Free developer accounts need to refresh sideloaded apps once a week or the certificates get revoked.
