### ISSUE TITLE
Sync Mangayomi on PC with mobile version

### ISSUE THREAD

**Issue by tanoopkumar** [kodjodevf/mangayomi#202]
### Describe your suggested feature

Potentially add the ability to make an account or create one with google. It could sync progress with both the desktop and mobile version of the app. For example, If I read up until x chapter on my laptop that progress would be synced on my phone, same with anime. That way extensions, chapter/episode progresses, and etc can be saved.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.

**Comment by pc-v2** [comment]
or local with pc as main server

**Comment by physispc** [comment]
Hi, is there some guidance to setup the sync server please ?
