### ISSUE TITLE
videos are not playing

### ISSUE THREAD

**Issue by ephraimzki** [kodjodevf/mangayomi#203]
i tried to play anime videos, it keeps on loading and it won't play.

**Comment by kodjodevf** [comment]
What source ?

**Comment by ephraimzki** [comment]
9anime, AllAnime, Kaido and HiAnime

**Comment by kodjodevf** [comment]
fixed!! 

for future issues regarding extensions please open an issue in the [extensions](https://github.com/kodjodevf/mangayomi-extensions/) repo
