### ISSUE TITLE
"Mangayomi" is not opening on pc

### ISSUE THREAD

**Issue by testbotbot2** [kodjodevf/mangayomi#206]
### Steps to reproduce

I encountered the same error every time I tried to open the app as usual by clicking on it.

### Expected behavior

 "It should open normally; however, that's not happening."

### Actual behavior

I tried to open it, but nothing happened. I also tried using the administrator, but still, nothing happened.

### Mangayomi version

v0.2.6

### Device

Lenovo ThinkPad L540

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by GithubUser314159** [comment]
can confirm same behavior in win10. reinstalling the previous version fixed the issue.

**Comment by Virusilvester** [comment]
v0.2.6 not opening on Windows 10, for now, use v.0.2.55 though you can't delete via galley but manually delete chapters or the folder.

**Comment by testbotbot2** [comment]
Seems like I'm not the only one facing similar issues.

**Comment by theprodigy2013** [comment]
Same here, Windows 11, 0.2.6, nothing happens on opening

**Comment by kodjodevf** [comment]
Fixed! check the latest release
