### ISSUE TITLE
[bug]I can't install the app.

### ISSUE THREAD

**Issue by tokumei123456** [kodjodevf/mangayomi#208]
### Steps to reproduce

1.Install the app from SideStore.
2.The message "An unknown error occurred" is returned and installation is not possible.
―――――――
1.Install using LiveContainer.
2.I get the message "Error while signing app" and cannot install.

### Expected behavior

![IMG_0802](https://github.com/kodjodevf/mangayomi/assets/171477482/23d2b59b-f494-4477-8089-c9de6e63027a)
![IMG_0801](https://github.com/kodjodevf/mangayomi/assets/171477482/780ca724-b75e-40cf-9471-61c966361ebb)

### Actual behavior

I can't install the app.

### Mangayomi version

0.2.6

### Device

iPad 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by Mj101906** [comment]
I also receiving installing issue telling me integrity error despite having the app uninstalled

**Comment by tokumei123456** [comment]
I was able to install it using Sideloadly.
But when I watch anime there is no sound.
