### ISSUE TITLE
Error installing ipa via AltStore

### ISSUE THREAD

**Issue by Nova-69** [kodjodevf/mangayomi#21]
Getting this error: - /Users/rileytestut/Developer/Projects/AltStore/Dependencies/AltSign/AltSign/ldid/../../Dependencies/ldid/ldid.cpp(1368): _assert(): end >= size - 0x10 - when trying to sideload with AltStore. Using an iPad Mini 5, on iPadOS 16.6.

**Comment by kodjodevf** [comment]
I don't think if this problem is related to the App
