### ISSUE TITLE
Error 'flutter_rust_bridge_codegen generate'

### ISSUE THREAD

**Issue by LiquidPlatypus** [kodjodevf/mangayomi#211]
### Steps to reproduce

Follow the "Using flutter_rust_bridge" section

![image](https://github.com/kodjodevf/mangayomi/assets/104024934/4bc1c3b8-e9a0-47e8-a945-d9fff0a0d78e)

### Expected behavior

Install the app.

### Actual behavior

It throw me this error

![image](https://github.com/kodjodevf/mangayomi/assets/104024934/60604dd5-4f5d-4533-9660-09dbf50e8258)

### Mangayomi version

0.2.6

### Device

Windows 11

### Other details

Just finishing installing Flutter and Android Studio (already have Rust apparently), and when I try to execute this command it show me this error.
Can't run the command 'flutter run' after cause it show me "Error: no pubspec.yaml file found."

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by kodjodevf** [comment]
sync fork to the latest changes it will solve this issue
