### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Akashi123-deep** [kodjodevf/mangayomi#212]
### Steps to reproduce

![IMG_20240626_171813](https://github.com/kodjodevf/mangayomi/assets/102795903/ee058834-aeb1-4daf-bfe9-9c24d50b634f)

### Expected behavior

Working fine

### Actual behavior

![IMG_20240626_171813](https://github.com/kodjodevf/mangayomi/assets/102795903/e71ccad6-dd55-439b-baed-3e43d70e6ef9)

### Mangayomi version

0.2.6

### Device

Redmi 10C android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by echofire26** [comment]
Seeing the same issue as reported by @Akashi123-deep - it started with Version 0.2.6 and continued in Version 0.2.7.  Some Manga extensions continue to function normally, while others return the dart_eval runtime error.  Uninstalling and reverting back to 0.2.55 seems to mostly correct the issue for now, but can't install the latest versions.  For further context I'm using the android-arm64-v8a.apk versions on the two devices I have.

To the devs - The app is really appreciated and I whole heartedly understand y'all are doing this on your own time.  So just want to say thank you regardless.

**Comment by Trashbitgameboy** [comment]
![Screenshot_20240708-234647](https://github.com/kodjodevf/mangayomi/assets/108297851/953dc202-8d0f-4782-9b0b-121196fa9d3f)

Same by me since 2.6

**Comment by mumiby** [comment]
> ![Screenshot_20240708-234647](https://private-user-images.githubusercontent.com/108297851/346732934-953dc202-8d0f-4782-9b0b-121196fa9d3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2Njc4MTQsIm5iZiI6MTcyMTY2NzUxNCwicGF0aCI6Ii8xMDgyOTc4NTEvMzQ2NzMyOTM0LTk1M2RjMjAyLThkMGYtNDc4Mi05YjBiLTEyMTE5NmZhOWQzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQxNjU4MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNGI3NGYxZjFlOWRlZjM0MzZhOTUwMmY1ZjM3NzUyNTRkOGU3NTkzNjM5NmVhZjg4MWQyNWE5OGY2OTk2YjhhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vqTIp2_rhT71MQBZALcMvzXiA5ItDDcyVo4uxPHTcIg)
> 
> Same by me since 2.6

Is that an extension issue? I get that with many extensions

**Comment by Trashbitgameboy** [comment]
:O

**Comment by kodjodevf** [comment]
Create your issues in extension section [https://github.com/kodjodevf/mangayomi-extensions](https://github.com/kodjodevf/mangayomi-extensions)

**Comment by echofire26** [comment]
> Create your issues in extension section [https://github.com/kodjodevf/mangayomi-extensions](https://github.com/kodjodevf/mangayomi-extensions)

Not trying to be a pain, just want to ask/verify, is the extension section really the correct place when this seems to affect multiple sources and version 2.55 and before does not have the issue.
