### ISSUE TITLE
Wrong Version und Last Download link

### ISSUE THREAD

**Issue by Trashbitgameboy** [kodjodevf/mangayomi#213]
### Steps to reproduce

See last Release an Match Version with Version you Download 

### Expected behavior

Download APK with Version 0.2.6

### Actual behavior

Wrong Download Release

### Mangayomi version

0.2.55

### Device

Google Pixel 5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by kodjodevf** [comment]
fixed!
