### ISSUE TITLE
Cannot download Android APK last release

### ISSUE THREAD

**Issue by jerome-antoine** [kodjodevf/mangayomi#216]
### Steps to reproduce

Just click on the links provided for download, either for arm64-v8a or armeabi-v7a.

### Expected behavior

Download is impossible due to error message returning.

### Actual behavior

Trying to download one of the 2 APKs provided for Android results in getting an error message which indicates that  no style information is associated with this XML file (see screenshot below).
Trying to download from any other link works without any problem, only those related to Android APKs have this problematic behaviour.

![Screenshot_20240629-141201](https://github.com/kodjodevf/mangayomi/assets/128973755/02afc329-0883-481b-a696-dc3e2468dcc2)

### Mangayomi version

0.2.7

### Device

Nothing Phone 1 (Spacewar)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by kodjodevf** [comment]
Just tested and it works

**Comment by jerome-antoine** [comment]
I have also retested it and now it works too...
I don't what the problem was but anyway thank you 😉
