### ISSUE TITLE
App won't launch on linux (new version 0.2.7)

### ISSUE THREAD

**Issue by K3vinb5** [kodjodevf/mangayomi#217]
### Steps to reproduce

When trying to launch I get this error
./Mangayomi-v0.2.7-linux.AppImage : error while loading shared libraries: libmpv.so: cannot open shared object file: No such file or directory

### Expected behavior

Should launch

### Actual behavior

Didn't launch

### Mangayomi version

0.2.7

### Device

Ubuntu Laptop, (Ubuntu 23.10)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by kodjodevf** [comment]
Fixed!!  try the latest release
