### ISSUE TITLE
Most recent (0.2.7) windows release triggers an antivirus response

### ISSUE THREAD

**Issue by theprodigy2013** [kodjodevf/mangayomi#219]
### Steps to reproduce

1. download either .exe or .zip
2. throw it into virustotal
3. https://www.virustotal.com/gui/file/bc6cb9b965fbdca284ae961fba499d8b49bd9feb2c73cc31a83c360bb49e5e34/detection

### Expected behavior

previous versions didn't trigger it

### Actual behavior

an antivirus response was triggered due to one of the .dll files, most likely a false positive

### Mangayomi version

0.2.7

### Device

MSI Windows 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by kodjodevf** [comment]
Retry with the latest
