### ISSUE TITLE
Chapters not loading on IOS - 2.6+ and up.

### ISSUE THREAD

**Issue by CycloneCX** [kodjodevf/mangayomi#220]
![image](https://github.com/kodjodevf/mangayomi/assets/14819312/fef4db64-4054-45bf-8265-9502eb32de91)

Had to revert to 2.55 again, can't use later versions until this issue is resolved.

**Comment by kodjodevf** [comment]
What source ?

**Comment by CycloneCX** [comment]
Sorry about the late reply, it seems fixed now in the lastest version.

But now I have a different issue I want to bring to your attention.

I don't know in which version it started but fullscreen appears to be broken.

**Comment by CycloneCX** [comment]
![image](https://github.com/user-attachments/assets/d6087a37-f07e-4f90-a85a-508589c72c05)

![image](https://github.com/user-attachments/assets/8278c980-407c-4ca9-b91a-16402b8bb221)

One of these is 2.0 where fullscreen works, there is no visible ui elements, 

Other one is version 2.7/2.75.

Fullscreen is broken/ui is always present st the bottom.

**Comment by kodjodevf** [comment]
fixed!  will be available in the next release

**Comment by CycloneCX** [comment]
I tried the latest just now, improved, but there is still a gray bar the bottom of the app visible.

**Comment by kodjodevf** [comment]
Mangaread.org and some sources seems to be okay now in the latest release.

For the gray bar that still visible create a new issue and join some screenshots
