### ISSUE TITLE
Resume button doesn’t play next episode

### ISSUE THREAD

**Issue by kyleyee52** [kodjodevf/mangayomi#221]
### Steps to reproduce

1. Finish watching an episode/reading a chapter
2. Click back button to exit current episode/chapter. Verify that the episode/chapter gets marked as completed
3. Click Resume button
4. Same episode/chapter that was just viewed gets opened instead of the next one

### Expected behavior

Resume button should take you to the next episode/chapter if the one being resumed is marked as completed.

### Actual behavior

Regardless of completion, the resume button takes you to the most recently viewed episode/chapter

### Mangayomi version

0.2.7

### Device

iPhone 12 Pro, iOS 16.1.2

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by Taliruls** [comment]
I've experienced this aswell with reading. after reading a number of chapters. once I resume it goes back to the first chapter I read of the batch.  

newly updated chapters also jump back to the previously read chapter
