### ISSUE TITLE
The program is not working

### ISSUE THREAD

**Issue by ccode-iin** [kodjodevf/mangayomi#223]
### Steps to reproduce

I downloaded the latest version of mangayomi but it doesn't work

### Expected behavior

I tried running it as administrator but it didn't work either and nothing appeared

### Actual behavior

The problem is that when I try to turn it on. Literally nothing happens. I tried downloading an older version (0.2.6) but even it didn't work for me.   
But older versions, such as (0.1.7) or lower, work for me, but nothing appears within the application, so I wanted to update it.

### Mangayomi version

(0.2.7)   and     (0.2.6)

### Device

HP EliteBook Windows 10 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by GottaLoveAng** [comment]
This is also happening on my Windows 11 installation. I opened task manager to look at the behavior and the application opens for a second then instantaneously closes.

**Comment by PSFaceLLC** [comment]
It happened to me too, as soon as I open the program in version 0.2.7 or 0.2.6 it closes immediately while the previous versions work fine, I tried to remove the real-time protection of windows defender but nothing changed :(

**Comment by kodjodevf** [comment]
Fixed!!  try the latest release
