### ISSUE TITLE
MSVCP140D.dll was not found

### ISSUE THREAD

**Issue by codeduph** [kodjodevf/mangayomi#227]
### Steps to reproduce

cannot open the app saying MSVCP140D.dll was not found

I already installed "Visual C++ Redistributable Runtimes All-in-One" and also install 2015 x64 x86... I also install & uninstall it BUT the problem stays the same...

![2024-07-17_163720](https://github.com/user-attachments/assets/bf3bd7d6-deb8-41df-8e19-8bcd524ed76e)

### Expected behavior

Should open the app

### Actual behavior

cannot open the app...

### Mangayomi version

v0.2.7

### Device

Windows 10 21H2 (OS Build 19044 2913)

### Other details

I've download a DLL still it doesn't open...

![13213123](https://github.com/user-attachments/assets/39a74a01-d9ce-41ae-b9b5-1643500ca517)

![1122](https://github.com/user-attachments/assets/c869270d-afb4-4aa3-a448-2602f75252a8)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by realgooseman** [comment]
v0.2.55 is the last working version on Windows 11, I've tried v0.2.6 and v0.2.7, they both don't work.

**Comment by kodjodevf** [comment]
Fixed!!  try the latest release
