### ISSUE TITLE
IOS18 UI out of place when reading

### ISSUE THREAD

**Issue by lamlados** [kodjodevf/mangayomi#229]
### Steps to reproduce

1. open a manga
2. UI out of place
3. When touching the screen center, UI turns good:
![Screenshot 2024-07-19 at 09 59 59](https://github.com/user-attachments/assets/78bef57e-15dc-40b9-a439-55df8bd0422f)
4. Then click the setting, `General` and `Custom filter` tabs don't reponse to click.

### Expected behavior

UI should be well structured

### Actual behavior

UI out of place
![IMG_5033](https://github.com/user-attachments/assets/5995a698-02e4-4b30-af99-9e23a5874493)

### Mangayomi version

0.2.75

### Device

iPhone 12, IOS 18 beta3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by lamlados** [comment]
Update: General and Custom filter tabs can be switched by swipe

**Comment by CycloneCX** [comment]
Can't hide the UI either, revert to earlier versions to hide it completely.

I'm on 2.0,UI is hidden completely in full-screen as it should be.

Later versions look like this:

![image](https://github.com/user-attachments/assets/1b3ae8b2-9df2-4364-9024-1dd878fdf6c9)

Old version:
![image](https://github.com/user-attachments/assets/6bb27313-2d00-463e-adfb-a826a6b8ad5e)

**Comment by CycloneCX** [comment]
Hoping he will fix it, or at least let us hide the UI again when fullscreen is on in the later versions. 

Will stick with the old version for now, no visible UI is better.
