### ISSUE TITLE
Option for having a sort option as default.

### ISSUE THREAD

**Issue by ProvokedGamer** [kodjodevf/mangayomi#23]
I like having my chapter/video lists start from the top and go down. I was wondering if you could add an option in settings to have the option to change the default sort order across all anime/manga so that you don't have to keep resorting it every time you go to an anime/manga. 

![image](https://github.com/kodjodevf/mangayomi/assets/119907145/e52416f7-d04c-41a8-87c1-09bec90c73de)

**Comment by kodjodevf** [comment]
OK it's noted
