### ISSUE TITLE
type '$MSource' is not a subtype of 'MProvider' in type cast

### ISSUE THREAD

**Issue by iddus** [kodjodevf/mangayomi#231]
### Steps to reproduce

1.open chapter
2.type '$MSource' is not a subtype of 'MProvider' in type cast

### Expected behavior

load chapter and start reading

### Actual behavior

type '$MSource' is not a subtype of 'MProvider' in type cast

### Mangayomi version

0.2.75

### Device

windows 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by kodjodevf** [comment]
what source ?
