### ISSUE TITLE
Getting error when opened a manga to read

### ISSUE THREAD

**Issue by AvAkanksh** [kodjodevf/mangayomi#233]
### Steps to reproduce

Just try to open any manga and any chapter from any of the sources, 

In my case I have tried a lot of them like Aqua scans(EN), and other english manga sources. 
![Screenshot_2024-07-26-09-26-13-99_6238686af4b6b7b1bc8710fa2688b07d](https://github.com/user-attachments/assets/37fb4b44-0689-46c7-8623-ac92dbd99697)

I am getting above error can anyone tell me what is the problem over here and how to fix it

### Expected behavior

Should be able to read the manga

### Actual behavior

The manga is not loading 

### Mangayomi version

0.2.75

### Device

Realme 9 pro plus

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by Slecarlier** [comment]
Hello, is there something to do to make work then? Try reload and unistall but still not working. Amazing app btw

**Comment by kodjodevf** [comment]
fixed!!
