### ISSUE TITLE
Can’t search any manga (CloudFlare)

### ISSUE THREAD

**Issue by WyxZer** [kodjodevf/mangayomi#234]
### Steps to reproduce

1. Select an extension that use cloudflare 
2. You get the error

### Expected behavior

You shouldn’t get any error and see the manga list.
Maybe use a popup to manually check cloudflare

### Actual behavior

No manga appear. Cant find any sources that work. Im using French extensions 
![IMG_2294](https://github.com/user-attachments/assets/c1d60696-f0aa-4d30-8ca9-8d1014b3020d)
![IMG_2293](https://github.com/user-attachments/assets/f87e4e1b-f7c0-4ffc-b6fe-20983f7767ef)

### Mangayomi version

0.2.75

### Device

iPhone 13 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by kodjodevf** [comment]
Give me an extension with which you encounter this error

**Comment by WyxZer** [comment]
PhenixScans have this error

**Comment by WyxZer** [comment]
Sorry to bother you but I have the exact same issue on Manga-Origines.fr (not the nsfw) even after the update. Hope you can fix it. It work fine on PhenixScans
