### ISSUE TITLE
windows11 can't install extension

### ISSUE THREAD

**Issue by xingsulianhen** [kodjodevf/mangayomi#237]
### Steps to reproduce

1. 
![image](https://github.com/user-attachments/assets/edd531bf-5685-442e-aa35-6a39af32ad0c)
2. 
![image](https://github.com/user-attachments/assets/62a59eff-a5e9-483e-9a42-b18fa9d524b4)

### Expected behavior

Extension should show in sources page

### Actual behavior

sources page is empty

### Mangayomi version

0.2.85

### Device

windows11 PC

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by ojvaj1** [comment]
Works for me. I got Windows 11 and tested it just now and works for manga and anime. Try reinstalling the program.
