### ISSUE TITLE
Libmpv not found in linux executable

### ISSUE THREAD

**Issue by pr0k41** [kodjodevf/mangayomi#24]
**./mangayomi: error while loading shared libraries: libmpv.so.1: cannot open shared object file: No such file or directory**
This error message is received while trying to run the executable, I tried reinstalling mpv , then installed mpv-full-git, and even built mpv with mpv-full-build-git.But the problem persists.

**Comment by kodjodevf** [comment]
Run this command before using the application : 
sudo apt-get install webkit2gtk-4.1 clang cmake ninja-build pkg-config libgtk-3-dev mpv libmpv-dev dpkg-dev
