### ISSUE TITLE
Formatexception: unexpected character (at character 1)

### ISSUE THREAD

**Issue by Madman2z** [kodjodevf/mangayomi#240]
### Steps to reproduce

first of all i do think that it's a problem with my system not the app. However i have no clue what this message entails as such if anyone knows what is the problem please let me know. the steps as follows:
1. open any anime extension.
2.  Choose any anime.
3. it shows 0 episodes and the following error.
![Screenshot 2024-08-07 194612](https://github.com/user-attachments/assets/2c0f4763-434c-43bf-8b55-6d87796ed5d7)

### Expected behavior

When clicking on an anime source and choosing a series, a list of available episodes should appear with the download button being available.

### Actual behavior

nothing shows with the error "Formatexception: unexpected character (at character 1)" 
![Screenshot 2024-08-07 194612](https://github.com/user-attachments/assets/6f65c6f8-047a-46d1-b7da-1a804bc3268e)

### Mangayomi version

all versions 

### Device

windows 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by Reichlandia** [comment]
I have the similar issue with another extension named SFLIX as whenever I tried to open any episode from a movie or a cartoon, it gives me the same error. I do not know if this would get fix compared to Aniwave (Aniwave got shut down days ago) but here's the screenshot 

![Screenshot 2024-09-15 005114](https://github.com/user-attachments/assets/d2f6ece8-1493-4c3c-be17-f3cd084572aa)


I hope this would get attention so I wouldn't have to create an another issue with the same bug error

**Comment by kodjodevf** [comment]
These issues are not related to the application but rather to the extensions

**Comment by Madman2z** [comment]
> These issues are not related to the application but rather to the extensions

Thank you for replying ,, i did update the extensions to the latest version and same with the application ,, yet that didn't fix it ,, not sure what to do but thanks for the effort you guys put into the app it's a great app and i'm sure it requires alot of work. keep up the good work and mad respect to you all.
