### ISSUE TITLE
Update Extension

### ISSUE THREAD

**Issue by Falind** [kodjodevf/mangayomi#243]
### Steps to reproduce

Can you pls update the sekaikomik extension

### Expected behavior
sekaikomik.pw is the newest version 

### Actual behavior

p

### Mangayomi version

beta 0.29

### Device

asus rog strix 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by Anandaiki** [comment]
> ### Steps to reproduce
> Can you pls update the sekaikomik extension
> 
> ### Expected behavior
> sekaikomik.pw is the newest version
> 
> ### Actual behavior
> p
> 
> ### Mangayomi version
> beta 0.29
> 
> ### Device
> asus rog strix
> 
> ### Other details
> _No response_
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
> * [x]  I have written a short but informative title.
> * [x]  If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
> * [x]  I have updated all installed extensions.

Pls add sekaikomik extension
