### ISSUE TITLE
Anime library doesn't load

### ISSUE THREAD

**Issue by KellZek** [kodjodevf/mangayomi#250]
### Steps to reproduce

1. Open the app
2. Go to "Anime" tab

### Expected behavior

When clicking on the Anime tab, the library containing favorited animes should load as intended

### Actual behavior

The library page doesn't seem to load

![Screenshot_2024-08-30-18-24-01-825_com kodjodevf mangayomi](https://github.com/user-attachments/assets/b01f9c7b-984a-415b-8e51-6d7115f62016)

### Mangayomi version

0.3.0

### Device

Xiaomi Redmi Note 11 Pro

### Other details

- Contrary to what someone suggested on the Discord server, disabling developer options doesn't seem to solve the issue
- This issue seems to also happen with the Manga library 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by kodjodevf** [comment]
To reproduce this issue I need you to share your backup

**Comment by KellZek** [comment]
[mangayomibackup.zip](https://github.com/user-attachments/files/17046271/mangayomibackup.zip)

Here's the backup!
