### ISSUE TITLE
cannot use manga library after adjusting sort

### ISSUE THREAD

**Issue by Badriluthfi** [kodjodevf/mangayomi#257]
### Steps to reproduce

1. adjust sort option to added date

### Expected behavior

page just become grey out cant click anything

### Actual behavior

unuseable page

### Mangayomi version

0.30

### Device

windows 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by kodjodevf** [comment]
To reproduce this issue I need you to share your backup
