### ISSUE TITLE
Arch linux build failed

### ISSUE THREAD

**Issue by BludAdit3220** [kodjodevf/mangayomi#258]
### Steps to reproduce

This will generate a JSON format file containing all messages that 
need to be translated.
Launching lib/main.dart on Linux in debug mode...
/home/sun_god_nika_luffy/mangayomi/linux/flutter/ephemeral/.plugin_symlinks/flutter_qjs/cxx/quickjs/quickjs.c:9843:16: error: incompatible pointer to integer conversion returning 'void *' from a function with result type 'JSClassID' (aka 'unsigned int') [-Wint-conversion]
/home/sun_god_nika_luffy/mangayomi/linux/flutter/ephemeral/.plugin_symlinks/flutter_qjs/cxx/quickjs/quickjs.c:10793:30: warning: implicit conversion from 'long' to 'double' changes value from 9223372036854775807 to 9223372036854775808 [-Wimplicit-const-int-float-conversion]
Building Linux application...                                           
Error: Build process failed

### Expected behavior

I expected the file to be builded when ran flutter run and yes i did run flutter_rust_bridge_codegen generate

### Actual behavior

it doesnt build the file

### Mangayomi version

5.6.6

### Device

I have arch linux and my device is hp laptop pavilion

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by kodjodevf** [comment]
fixed, you can try to build again
