### ISSUE TITLE
My library is blank after i tapped latest chapters.

### ISSUE THREAD

**Issue by Nifrimis** [kodjodevf/mangayomi#259]
### Steps to reproduce

I canot see the library after i tapped latest chapters, only a grey screen is there.
![Screenshot_20240918_090731](https://github.com/user-attachments/assets/3ee74181-cb00-42d5-a892-1a5e7b3a1cb9)
![Screenshot_20240918_090731](https://github.com/user-attachments/assets/9ab93bc7-2b67-4276-aacf-674032566a47)

### Expected behavior

I shoule be able to see the mangas i add to my library but my manga library is shown blank.

### Actual behavior

I tapped the latest chapters in my manga library but then my screen library turned blank.

### Mangayomi version

The latest version

### Device

Samsung a35 5g 

### Other details

![Screenshot_20240918_090731](https://github.com/user-attachments/assets/e85407da-69ed-4f67-b03c-beacd378c288)
I love this app, i want to read my manhwas please fix it for me.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by Nifrimis** [comment]
Someone please help TT

**Comment by Schnitzel5** [comment]
@Nifrimis do you mind sharing your backup, so maybe I can reproduce it on my side and try to fix the bug causing that.
