### ISSUE TITLE
Cannot install any extensions.

### ISSUE THREAD

**Issue by cpAtor** [kodjodevf/mangayomi#26]
OS: Android 13
App Version: 0.0.45

When I tap install for any extension, the spinner shows up for a sec and nothing happens.

Please let me know if you need any more information.

**Comment by kodjodevf** [comment]
I just tested it on my side no problem, could you send me a video screenshot of the problem you are experiencing?

**Comment by cpAtor** [comment]
https://github.com/kodjodevf/mangayomi/assets/25845207/29c6d487-9cf9-4261-8954-1f23a8c0fe3c

Added a recording of what is happening when I tap install. Please let me know if you need any other info.

**Comment by kodjodevf** [comment]
This problem still persist ?

**Comment by cpAtor** [comment]
Yes, it still persists. Is there a new release?

**Comment by kodjodevf** [comment]
Yes, you can check in the latest release.

**Comment by cpAtor** [comment]
I have tried with v 0.0.47. I am still unable to install any extensions.
