### ISSUE TITLE
Anime crashing on IOS everytime

### ISSUE THREAD

**Issue by tyrohellion** [kodjodevf/mangayomi#27]
IOS versions tested: 16.6, 17.0
iPhone model: 13 Pro
Sideloaders used: Scarlet and Sideloadly
How to recreate: Watch any anime on any server from any of the english providers and at around the 1 minute mark the app always full crashes

Suggestion: Also an option in settings to auto select Sub over Dub would be great because everything defaults to dub

App looks really good so far though thanks for your work :)

**Comment by kodjodevf** [comment]
Noted !  will check the issue

**Comment by kodjodevf** [comment]
Fixed, you can check in the latest release
