### ISSUE TITLE
cancel filter caused the unloaded parts turn grey

### ISSUE THREAD

**Issue by yxxyun** [kodjodevf/mangayomi#274]
### Steps to reproduce

After the filter modal popped up, instead of performing the filtering, cancel it and caused the unloaded parts of the main window to turn grey.

### Expected behavior

refresh or continue loading

### Actual behavior

![20241008091114](https://github.com/user-attachments/assets/720e70f7-1946-47d4-91e2-decd8bb1e9cf)

### Mangayomi version

0.3.55

### Device

windows, iOS

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by yxxyun** [comment]
With latest change, cancel filter causes the unloaded parts turn red.

**Comment by yxxyun** [comment]
<img width="960" alt="20241113193602" src="https://github.com/user-attachments/assets/77ecbef0-516a-459e-865d-fb6b410a1489">

**Comment by kodjodevf** [comment]
fixed!
