### ISSUE TITLE
iOS ipa file doesn’t work

### ISSUE THREAD

**Issue by Whisper-err** [kodjodevf/mangayomi#280]
### Steps to reproduce

So basically i downloaded the ipa file and using a sideloader called Altstore i tried sideloading the ipa file onto my iphone (you cant install an ipa file without a sideloader) and i keep getting an error. I tried altstore and sidestore, it doesnt work on both.

### Expected behavior

What should happen is there should be no error.

### Actual behavior

What you should expect is an error after trying to install/sideload the ipa file onto the iphone

### Mangayomi version

v0.3.55

### Device

iPhone 15 Pro Max, iOS 18.1 beta 6 (developer beta)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by LightSky10006** [comment]
same here. Plus, tried v0.3.5 and it's the same.

**Comment by kuki29123** [comment]
same.

**Comment by yxxyun** [comment]
Try sideloadly
