### ISSUE TITLE
[Site Request] Yugenmangas

### ISSUE THREAD

**Issue by djgerman10** [kodjodevf/mangayomi#3]
Name of the website
YugenMangas

Website urls (examples below)

Site:
https://yugenmangas.com/
Manga List:
https://yugenmangas.com/series
https://yugenmangas.com/novelas
Manga example:
[https://yugenmangas.com/series/en-esta-vida-sere-la-matriarca](https://yugenmangas.com/series/en-esta-vida-sere-la-matriarca)
Chapter online viewer example:
https://yugenmangas.com/series/en-esta-vida-sere-la-matriarca/capitulo-47
Languages
Spanish

*By the way I congratulate the creator of this application.
I have high expectations especially for being multi platform.

**Comment by kodjodevf** [comment]
The YugenMangas source has been added you can download the latest version of the app to use it
