### ISSUE TITLE
Some anime cannot be downloaded

### ISSUE THREAD

**Issue by Rafuuxx** [kodjodevf/mangayomi#30]
![IMG_0063](https://github.com/kodjodevf/mangayomi/assets/145273174/664a3dbb-f262-4b94-bf6e-a41dac632b73)

Download option is still broke on iphone 

And need discord server for info

**Comment by kodjodevf** [comment]
Oh I see, actually you can only download anime from **Gogoanime** source due some video sources format are mp4 all videos sources format from **Kaido** or **AniWatch** are .m3u8 .

**Comment by kodjodevf** [comment]
As I said you can only download videos in .mp4 format and among them also others do not work, any contributions are welcome if you have knowledge on how to download videos.m3u8 or anything else concerning the project.
