### ISSUE TITLE
iPhone heating up and draining battery on newer .ipa builds (later than v0.3.6)

### ISSUE THREAD

**Issue by kashrtx** [kodjodevf/mangayomi#309]
### Steps to reproduce

1.	Install MangaYomi version later than v0.3.6.
	2.	Select AnimePahe and HiAnime as sources.
	3.	Enable MyAnimeList tracking.
	4.	Add anime to the library.
	5.	Play episodes using either sources and observe heating and battery drain. It may happen on any random episode.

### Expected behavior

The app should function normally without causing excessive heating or battery drain. Should be stable like 0.3.6.

### Actual behavior

When episode is playing the iphone slowly starts to heat up and experiences rapid battery drain during use.  It starts to cool down and stop draining when app is closed.

### Mangayomi version

0.3.7

### Device

iPhone 15 Pro Max on IOS 17.4.1

### Other details

Had no issues with older builds. The new features added after 0.3.6  have a bug that causes more load. I just started experiencing this in v0.3.65 and v0.3.7. Will downgrade back to 0.3.6.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by NBA2K1** [comment]
I also have this issue on an iPhone 7 with iOS 15.8.3, except I use AniWorld as source, not AnimePahe and HiAnime.
