### ISSUE TITLE
Webview not working

### ISSUE THREAD

**Issue by M-lang23** [kodjodevf/mangayomi#319]
### Steps to reproduce

1. Open Any entry 
2. Press Open in browser

### Expected behavior

It Should open webview

### Actual behavior

It Crashes

### Mangayomi version

0.375

### Device

HP Elitedesk G100 SFF Win11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by NBA2K1** [comment]
Same for me on Windows 10 22H2 Build 19045.5131

Webview works on Linux (Mint 22 Cinnamon) tho.

**Comment by NBA2K1** [comment]
Wanted to fix this. Started the debugger and it just works there.
