### ISSUE TITLE
[iOS] can't install - AltStore

### ISSUE THREAD

**Issue by bachig26** [kodjodevf/mangayomi#32]
#### Info
Device: iPhone SE 1st Gen (iOS 15.17.9) | iPhone SE 3rd Gen (iOS 17.0.3)
Mangayomi Version: 0.0.45

I tried installing on my both iOS devices but I get the same error message that I have attached below.

#### Error Message from AltStore
```
Error Code
AltSign.Error.0

Error Description
/Users/rileytestut/Developer/Projects/AltStore/Dependencies/AltSign/AltSign/ldid/../../Dependencies/ldid/ldid.cpp(1368): _assert(): end >= size - 0x10

Failure Reason
/Users/rileytestut/Developer/Projects/AltStore/Dependencies/AltSign/AltSign/ldid/../../Dependencies/ldid/ldid.cpp(1368): _assert(): end >= size - 0x10

Title
Failed to Install Mangayomi

Source File
ALTSigner.mm

Source Line
475
```

**Comment by bachig26** [comment]
@kodjodevf I believe the app minimum version is 13.0, but I think this isn't the issue in my case.

can you please look into the issue...🙏🙏🙏

**Comment by bachig26** [comment]
@kodjodevf some of my friends also mentioned me that they 're also facing this same issue where they can't install the app.

**Comment by kodjodevf** [comment]
I will check on my side. Have you checked with the old versions?

**Comment by bachig26** [comment]
> I will check on my side. Have you checked with the old versions?

no, I just installed the latest version (0.0.45) and never tried the older versions.
maybe I'll try them later to check if the issue persisted in older versions too.

**Comment by bachig26** [comment]
> I will check on my side. Have you checked with the old versions?

I have just tried every available IPa's from v0.0.25 till the recent version 0.0.46, I'm getting the same error message.

**Comment by kodjodevf** [comment]
Unfortunately I can't figure out exactly what the problem is.
On the other hand, a solution exists which is that of the [3uTools](https://www.3u.com/) tool which allows you to install it.

**Comment by MidnightKittenCat** [comment]
Getting the same error, still no fix?

**Comment by LooneyXIII** [comment]
![SideStore](https://github.com/kodjodevf/mangayomi/assets/7672659/f9100bda-43c3-4a82-9b83-044fda2495f3)
For me its with Sidestore, i can manage to push it with Sideloadly but it would be better with Sidestore so we can manage de Expiration

**Comment by Battler624** [comment]
Sorry for reviving this closed issue but I am having the same issue on ios 18 beta 8. iPhone 13 Pro
