### ISSUE TITLE
How to fix failed to bypass cloudflare 

### ISSUE THREAD

**Issue by ramizz7** [kodjodevf/mangayomi#321]
### Steps to reproduce

It says 403 failed to bypass cloudflare 
![IMG_0036](https://github.com/user-attachments/assets/e0c4885e-a27a-409c-9281-32951cce3bf5)
flare 

### Expected behavior

To fix this, also if possible can you guys add more manga extension please

### Actual behavior

![IMG_0036](https://github.com/user-attachments/assets/e03c8c12-4a93-4a73-9f9f-7099a50c2d7f)

### Mangayomi version

0.3.75

### Device

Model: MPQ03NF/A      iPad: 17.5.1

### Other details

![IMG_0036](https://github.com/user-attachments/assets/108aa18f-205f-49e7-8ffd-7430a0193892)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by kodjodevf** [comment]
What source did you use ?

**Comment by ramizz7** [comment]
> What source did you use ?

IsekaiScanManga (unoriginal)

**Comment by kodjodevf** [comment]
This is an extension issue not app issue, open the issue [here](https://github.com/kodjodevf/mangayomi-extensions)

**Comment by ramizz7** [comment]
> This is an extension issue not app issue, open the issue [here](https://github.com/kodjodevf/mangayomi-extensions)

Okay
