### ISSUE TITLE
[Windows] Player Stuttering

### ISSUE THREAD

**Issue by bachig26** [kodjodevf/mangayomi#33]
App Version: 0.0.45
Windows: 10

The App itself is smooth and I didn't have any issue, but when I tried to play a video and the video starts to get stutter at every frame.

### Steps:
1. Search any Anime title in any Source
2. Play a episode (in my case, Kage no Jitsuryokusha ni Naritakute! Season 2 Episode 1)
3. see the Bug (Video starts to play and then it gets stutter at every frame).

**Comment by kodjodevf** [comment]
Fixed, you can check in the latest release
