### ISSUE TITLE
Import

### ISSUE THREAD

**Issue by 99KJM** [kodjodevf/mangayomi#34]
How do I import a list whenever I try to import a list there are no options I exported from mal and anilist none are working for me

**Comment by kodjodevf** [comment]
I didn't understand your problem very well, can you describe it correctly with a screenshot if possible?

**Comment by 99KJM** [comment]
![image](https://github.com/kodjodevf/mangayomi/assets/146641100/f05110eb-aedc-4d3b-96a9-1da89eef76da)

![image](https://github.com/kodjodevf/mangayomi/assets/146641100/7a6db77b-41c2-47fb-b294-176dbe71eb40)

I am unable to import my lists

**Comment by kodjodevf** [comment]
This functionality is intended for reading local files such as:
 - for manga (.cbz, .zip)
 - for anime (.mkv, .mp4, ...)
