### ISSUE TITLE
Support for altsign

### ISSUE THREAD

**Issue by Nb11111111** [kodjodevf/mangayomi#344]
### Describe your suggested feature

Please make it work with AltStore and SideStore 

### Other details

This is the error when installing 
/Users/runner/Library/Developer/Xcode/DerivedData/AltStore-dunvejkuqerofjghtqolpzgexuyv/SourcePackages/checkouts/AltSign/Sources/ldid/../ldid-core/ldid.cpp(1368): _assert(): end >= size - 0x10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.

**Comment by yxxyun** [comment]
Use Sideloadly or LiveContainer.  This should be done by AltStore and SideStore.
