### ISSUE TITLE
Aniwatch (latest anime not synced)

### ISSUE THREAD

**Issue by 99KJM** [kodjodevf/mangayomi#38]
On the latest it isnt really synced up with the actual modules latest so here is what the recently looks like here

<img width="963" alt="Screenshot 2023-10-27 at 12 16 53 AM" src="https://github.com/kodjodevf/mangayomi/assets/146641100/88963a8a-2bce-4ad8-b19b-dd8746eb7311">

and here is what it looks like on the app

![image](https://github.com/kodjodevf/mangayomi/assets/146641100/54a54006-5b55-43c2-9c61-202c6f9ac794)

so it really isnt matching up

**Comment by kodjodevf** [comment]
Ok I will check it

**Comment by kodjodevf** [comment]
Fixed !!
