### ISSUE TITLE
Anilist tracking is not synced after episode or chapter is completed

### ISSUE THREAD

**Issue by iindicaa** [kodjodevf/mangayomi#46]
When I finish a anime episode it will not track when 100% finished or for manga tracking when chapter 100% finished too.

Ex:
![Uploading IMG_3859.
![IMG_3860](https://github.com/kodjodevf/mangayomi/assets/136735996/28b2389c-7020-4f09-b5bd-8e7f2bfcd500)
png…]()

**Comment by kodjodevf** [comment]
This isn't really a problem because this feature isn't available yet. For now you can only sync manually
