### ISSUE TITLE
Backup and Restore feature for library items

### ISSUE THREAD

**Issue by ajtazer** [kodjodevf/mangayomi#47]
### Describe your suggested feature

_**Currently, Mangayomi lacks a built-in backup and restore mechanism for library items and extensions. This exposes users to the risk of losing their carefully curated collections and personalized configurations, especially when formatting their devices or encountering data loss.**_

Here are some additional details about the full backup and restore feature:

# Backup:

- Users should be able to manually trigger a full backup at any time.
- Backups should be stored locally on the device.
- The backup should include all user data, including bookmarks, read progression, user settings, and any extensions or themes installed.

# Restore:

- Users should be able to restore their data from a full backup at any time.
- The restore process should be easy to use and should not require any technical knowledge.
- Restoring from a backup should overwrite any existing data on the device, ensuring the user has the latest data.

# Additional considerations:
- Implement a backup schedule feature to allow users to automatically backup their data at regular intervals.
- Clearly communicate the backup and restore process to users through tutorials and documentation.

[This Might help in understanding the issue](https://github.com/tachiyomiorg/tachiyomi/pull/212)

Thanks for Reading

### Acknowledgements

- [x] I have written a short but informative title.
- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.

**Comment by kodjodevf** [comment]
Feature implemented in #53, you will be able to use it in the next realease.
