### ISSUE TITLE
Option to disable tap navigation 

### ISSUE THREAD

**Issue by hidden12323** [kodjodevf/mangayomi#59]
### Describe your suggested feature

A option to disable the tap navigation would be great because I always accidentally trigger it by simply scrolling the page 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.

**Comment by kodjodevf** [comment]
Duplicated issue #54
