### ISSUE TITLE
Preloading of images

### ISSUE THREAD

**Issue by paradojaaa** [kodjodevf/mangayomi#6]
Hello, 
thanks for your work. 

The reading experience could be improved if, in the non-downloaded chapters, the images following the one you are reading were preloaded, so that when you go to the next page there is not a black screen and have to wait for it to load.

Also, I don't know if it's related, when you read laterally with the chapter downloaded, when you move to the next page by tapping not swiping, the black screen appears briefly and then loads the image.

**Comment by kodjodevf** [comment]
Noted, this will be fixed in the next release.
