### ISSUE TITLE
Remove gaps between pages when reading a webtoon 

### ISSUE THREAD

**Issue by hidden12323** [kodjodevf/mangayomi#60]
### Steps to reproduce

Open a webtoon and scroll to the end of the page 

### Expected behavior

No gaps between pages 
![IMG_5377](https://github.com/kodjodevf/mangayomi/assets/137211750/131b8930-5852-4a55-820f-2cd50f8f18d4)

### Actual behavior

Gaps between pages 

### Mangayomi version

0.1.1

### Device

iPhone 12 iOS 17

### Other details

That’s how it looks like in the app currently 
![IMG_5378](https://github.com/kodjodevf/mangayomi/assets/137211750/eeb76331-1da1-4977-8b95-07d9420fa370)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by kodjodevf** [comment]
I'll fix it in the next release.

**Comment by kodjodevf** [comment]
Fixed in the latest release
