### ISSUE TITLE
This is awesome, finally a good iOS Manga reader.

### ISSUE THREAD

**Issue by CycloneCX** [kodjodevf/mangayomi#61]
### Describe your suggested feature

Thank you for all of the hard work. 🙏🏻

I have been using Mangareader for a while, and I was there when Paperback started out.

Sadly I didn’t like the Ui/Interface as much, and it was a little cumbersome to use.

This project looks awesome however.

I hope you consider creating an easily accessible “Favourites Manga tab.” 

There’s also another feature that is really good that we don’t have in iOS manga apps, and that is “continuous scrolling.” 

So that when you scroll down on a “continued vertical” style, it continues to scroll at whatever speed you were swiping, and it does not stop until you reach the end or tap the screen.

Essentially a “dynamic auto scroll” would this be hard to implement as a feature?

Keep up the great work! Hoping to move away from Mangareader.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.![image](https://github.com/kodjodevf/mangayomi/assets/14819312/25197066-50e6-4aef-b578-1ef762106106)

**Comment by kodjodevf** [comment]
Glad you like it, for the dynamic scroll I'll take a look and see how I can implement it.

**Comment by CycloneCX** [comment]
Awesome! 

That's wonderful, do you think there is a chance you will add a tab for flagged/favourite manga as well down the line?

I also tried the anime functionality out of curiosity and I was unable to select the "subbed" version with aniwave when there was a dub present.

Just thought I should provide feedback.

Already saw someone request airplay, is that still part of the plan? 👍🏻

This app is already pretty awesome, few tweaks here and there and it's probably good enough to be my daily driver for both!

**Comment by CycloneCX** [comment]
Would it be hard/possible to make auto scroll stop temporarily while a finger touches the reader?

And then resume of course, when you let go?
