### ISSUE TITLE
Unable To Sideload Via AltStore

### ISSUE THREAD

**Issue by ma-ideh** [kodjodevf/mangayomi#62]
### Steps to reproduce

![image](https://github.com/kodjodevf/mangayomi/assets/122187151/8f3db2e8-35a1-4d2d-9963-8f76ea315685)

### Expected behavior

n/a

### Actual behavior

n/a

### Mangayomi version

n/a

### Device

iPhone 15 Pro Max, 17.1.2

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by CasuallyGamin** [comment]
how to fix this?
