### ISSUE TITLE
Pause/Play Button or gesture whenever auto scroll is enabled.

### ISSUE THREAD

**Issue by CycloneCX** [kodjodevf/mangayomi#64]
### Describe your suggested feature

Maybe an easy access Play/Pause button somewhere above the quick page selector?

Preferably easily accessible, or even a gesture.  

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.

**Comment by kodjodevf** [comment]
This will be added

**Comment by kodjodevf** [comment]
Added
