### ISSUE TITLE
iOS 17 Crashes

### ISSUE THREAD

**Issue by XeonFaux** [kodjodevf/mangayomi#65]
### Steps to reproduce

Install Mangayomi via TrollStore 2.0.8
Launch Mangayomi
Crash

### Expected behavior

Opens the application normally.

### Actual behavior

Crashes upon opening.

### Mangayomi version

0.1.35

### Device

iPhone 13 Pro iOS 17.0 (21A329)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by kodjodevf** [comment]
can you give me the status, is this problem still happening ?

**Comment by CycloneCX** [comment]
I have the latest version, same Phone (13 Pro Max) same OS, not crashing for me.

**Comment by kodjodevf** [comment]
Thank you for your comment, so I will close the issue.

**Comment by XeonFaux** [comment]
Yes still an issue for me, re-installed the app several times, cleared app data, restarted phone.
