### ISSUE TITLE
Support for the swipe to go back gesture on IOS

### ISSUE THREAD

**Issue by tyrohellion** [kodjodevf/mangayomi#68]
### Describe your suggested feature

It would be great if the app supported IOS’s back gesture. The one where you swipe from the left of the screen to go back.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.

**Comment by kodjodevf** [comment]
Can you give an example

**Comment by tyrohellion** [comment]
> Can you give an example

https://github.com/kodjodevf/mangayomi/assets/51808054/d9851e18-8197-4e17-89ba-4e4757bb54c4
