### ISSUE TITLE
Backup/Restore Feature not working on iOS

### ISSUE THREAD

**Issue by User89182** [kodjodevf/mangayomi#72]
### Steps to reproduce

https://github.com/kodjodevf/mangayomi/assets/122187151/d93d0f5f-1123-43f9-bd8d-fdc93d466c0a

### Expected behavior

Should actually backup the app data and be able to restore it.

### Actual behavior

App crashes whilst not backing/restoring the apps data.

### Mangayomi version

0.1.4

### Device

iPhone 15 pro max

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by phamduyphat** [comment]
It was said to be fixed in [#56 ](url) which was my issue. I have verified automatic backup works after the fix but still not manual backup so maybe it's a file permission issue or a bad string formatting? The default backup location doesn't have any spaces.

**Comment by kodjodevf** [comment]
Fixed !!
