### ISSUE TITLE
How to add the external resources, like from Tachiyomi? Can you add some manga and anime resources in Chinese?

### ISSUE THREAD

**Issue by Jokervvv9** [kodjodevf/mangayomi#74]
### Describe your suggested feature

Good day!
Could we add the external resources from a subscription address, like from Tachiyomi?
Could you add some manga and anime resources in Chinese?
Like: 
https://www.baozimh.com/
https://copymanga.site/
http://www.ntdm9.com/

Big thanks!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.

**Comment by kodjodevf** [comment]
If you want to tell how to add external source, read this: https://github.com/kodjodevf/mangayomi-extensions/blob/main/CONTRIBUTING.md
