### ISSUE TITLE
Unable to Download Anime

### ISSUE THREAD

**Issue by phamduyphat** [kodjodevf/mangayomi#77]
### Steps to reproduce

1. Open the Mangayomi app.
2. Navigate to an anime series.
3. Click on an episode to download it.
4. Observe that the download starts but never completes. 

### Expected behavior

* Upon selecting an episode for download, the download should start and complete successfully, allowing me to watch the episode offline.

### Actual behavior

* When I select an episode for download, the download never starts. Download isn't added in queued....

### Mangayomi version

0.1.4

### Device

IpX 14.6 Troll Store + Win 11 23H2 

### Other details

* Not sure if it's an extension problem or the main app but animes still plays normally.
* Have tried with 3 ISPs and cellular

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by kodjodevf** [comment]
Not all anime can be downloaded it does not depend on the application but rather on the available server links which can be downloaded from a source, for others you can only stream the video.
