### ISSUE TITLE
Comick isn't loading manga after 3 rows

### ISSUE THREAD

**Issue by anotherduckling** [kodjodevf/mangayomi#8]
The pc version looks really good. Full android experience. But facing issue while loading manga in comick. It's showing error after 3 row. It's only happening when I click the latest filter. 

![image](https://github.com/kodjodevf/mangayomi/assets/57977673/7f37b969-2328-4a7f-a05d-07bb5ddc517c)

Also is it possible to add mangadex and crop pages feature?

**Comment by anotherduckling** [comment]
Also it's not expandable.
![image](https://github.com/kodjodevf/mangayomi/assets/57977673/941b7ee6-4f2b-44f2-956b-cc43989ce3e8)

**Comment by kodjodevf** [comment]
The MangaDex source has been added you can download the latest version of the app to use it
