### ISSUE TITLE
Latest episodes not showing

### ISSUE THREAD

**Issue by SukunaCodes** [kodjodevf/mangayomi#81]
### Steps to reproduce

Greetings, First I'd like to thank the developer @kodjodevf for this amazing app. I somehow stumbled upon it by accident😅 but it has been my main anime streaming platform.
Ok, so I've been trying to stream the latest episodes from JJK, Under Ninja, Eminence in Shadow S2 among others but I get the list to like 1-2 episodes behind the latest episode.
The image below will help I hope[current episode as of this thread is episode 12]...
![Eminence](https://github.com/kodjodevf/mangayomi/assets/67829913/9b0f1eda-90df-4c51-9612-2028d0683682)

### Expected behavior

I'm guessing the expected behaviour will be having the recent released episode. 

### Actual behavior

![Eminence](https://github.com/kodjodevf/mangayomi/assets/67829913/0484364c-e8f6-47a1-a258-b10c8b82c265)
I'm expecting episode 12 but I get episode 11, and it released 3 days ago.

### Mangayomi version

0.1.51

### Device

Windows 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by kodjodevf** [comment]
You need to click on refresh button to get the latest episodes

**Comment by SukunaCodes** [comment]
Thanks
