### ISSUE TITLE
Video player? 

### ISSUE THREAD

**Issue by lavara123** [kodjodevf/mangayomi#82]
### Steps to reproduce

Android phone big size not see icon
![IMG_20231224_091735](https://github.com/kodjodevf/mangayomi/assets/12005386/b2524688-fb85-4993-8a3d-779795dd5eba)
![IMG_20231224_091800](https://github.com/kodjodevf/mangayomi/assets/12005386/1b338de3-940b-43ab-bf8a-a12decc6d275)

### Expected behavior

Subtitle icon not see big size screen 

### Actual behavior

Subtitle icon not see big size screen 

### Mangayomi version

Last 

### Device

Nubia Red Magic 8 Pro 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by kodjodevf** [comment]
Fixed!
