### ISSUE TITLE
Video player skips on IOS with aniwave extension

### ISSUE THREAD

**Issue by tyrohellion** [kodjodevf/mangayomi#83]
### Steps to reproduce

I attached a video of it happening. I haven’t tested other extensions, but basically after a certain amount of time watching like 10 minutes or so the video will randomly skip a part and you can’t go back to see what you missed. The reason I didn’t open this issue in the extension repository is because I’m not sure if it’s a problem with the extension or not

https://github.com/kodjodevf/mangayomi/assets/51808054/1bb9b989-3a18-4194-b9e3-9a582a6294f4

platform: IOS 17.0
Phone: iPhone 13 Pro
Version: 0.1.51
Extensions tested: Aniwave
Sideloader used: Sideloadly

### Expected behavior

Video should only skip when the user inputs

### Actual behavior

Video skips after a certain amount of time randomly

### Mangayomi version

0.1.51

### Device

iPhone 13 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.[]()

**Comment by GodDraken** [comment]
This happens with gogo anime as well. It skips forward like 8 seconds randomly and when you try to rewind it still skips it forward. I'm on IOS 16.7.2

**Comment by kodjodevf** [comment]
Does it often happen that it skip ?

**Comment by GodDraken** [comment]
> Does it often happen that it skip ?

It happened to me twice in the same episode of "The Kingdoms of Ruin." If you close the episode and reopen it, it doesn't skip the part anymore which is kind of odd.

**Comment by kodjodevf** [comment]
Ok, I will try to reproduce the problem

**Comment by GodDraken** [comment]
Uploading RPReplay_Final1703790214.mp4…

**Comment by GodDraken** [comment]
https://github.com/kodjodevf/mangayomi/assets/153966766/0688b0fd-30d8-4bfc-a5e9-9a8f6e272a92

**Comment by kodjodevf** [comment]
Fixed! you can check in the latest release
