### ISSUE TITLE
Skip forward time

### ISSUE THREAD

**Issue by GodDraken** [kodjodevf/mangayomi#84]
### Describe your suggested feature

Add a feature to the player setting to make the fast forward time customizable. It could be set up like the opening skipper feature and have skip forward times like 1s, 3s, 5s, etc.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.

**Comment by kodjodevf** [comment]
Added!
