### ISSUE TITLE
DOWNLOADING

### ISSUE THREAD

**Issue by AnimeLove6** [kodjodevf/mangayomi#85]
### Steps to reproduce

I have a hard time downloading dubbed anime videos so I can watch offline 

### Expected behavior

.

### Actual behavior

.

### Mangayomi version

.

### Device

.

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by GodDraken** [comment]
This is kinda an issue with gogo and aniwave. aniwave downloading it slightly buggy and gogo just doesnt start.

**Comment by kodjodevf** [comment]
Fixed !!
