### ISSUE TITLE
Mangayomi AppImage on Linux is unable to find libmpv.so.1 and fails to run.

### ISSUE THREAD

**Issue by mizi3** [kodjodevf/mangayomi#86]
### Steps to reproduce

Have mpv version 1:0.36.0-1 for x86_64
Use a version of Linux that is up to date/rolling release like Arch, EndeavourOS etc...
Then run the appimage directly (or extract and run)

### Expected behavior

The app should run.

### Actual behavior

The application doesn't run, it returns the error:
`error while loading shared libraries: libmpv.so.1: cannot open shared object file: No such file or directory`

Versions of libmpv on EndeavourOS (and Arch):
![image](https://github.com/kodjodevf/mangayomi/assets/155194933/2a3924c9-56d5-4493-a189-782c308890e1)

Temporary fix is to symbolically link libmpv.so to libmpv.so.1
`sudo ln -sf /usr/lib/libmpv.so /usr/lib/libmpv.so.1`
but Im really not a fan of fixes like these as they quickly become messy and can cause system conflicts.

### Mangayomi version

v0.1.55-linux

### Device

Linux PC x86_64 EndeavourOS (1:1 parity to Arch linux)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by kodjodevf** [comment]
Are you still facing this problem?

**Comment by sweetbbak** [comment]
Nope! all good now. Thank you. (Im the same person btw)

**Comment by feelingwalnut** [comment]
i did encounter this on debian trixie a week or so ago. version 0.1.61
once you make the symbolic link, it wont need made again but it is a messy solution.
