### ISSUE TITLE
Request for Manga Extension Inclusion from Tachiyomi

### ISSUE THREAD

**Issue by ImpenetrableNoble** [kodjodevf/mangayomi#88]
### Describe your suggested feature

Hi Mangayomi, 

I'm an avid user of MangaYomi and greatly appreciate the incredible work your team has put into creating such a powerful manga reading application.

I would like to bring to your attention the availability of manga extensions from the Tachiyomi mobile application, which are not currently integrated into MangaYomi. Tachiyomi has a rich selection of extensions that could enhance the overall manga reading experience for MangaYomi users.

You can find the list of Tachiyomi extensions at the following link: [Tachiyomi Extensions]
( https://tachiyomi.org/extensions/ )

By incorporating these extensions into MangaYomi, users would have access to an even broader range of manga titles, enriching their reading options and contributing to a more comprehensive manga library within the application.

I understand the challenges associated with implementing new features, but I believe this addition would greatly benefit the MangaYomi community.

### Other details

Thank you for considering this request, and I look forward to witnessing the continued growth and improvement of MangaYomi.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.

**Comment by kodjodevf** [comment]
It is impossible to use them directly, all we could do is convert them to dart source by source
