### ISSUE TITLE
Urgent: Issue with Restoring Tachiyomi Backup Files in MangaYomi

### ISSUE THREAD

**Issue by ImpenetrableNoble** [kodjodevf/mangayomi#89]
### Steps to reproduce

1. Create a backup file in Tachiyomi.

2. Attempt to restore the backup file in MangaYomi.

### Expected behavior

MangaYomi should recognize and seamlessly restore backup files created by Tachiyomi.

### Actual behavior

MangaYomi fails to recognize the Tachiyomi backup file, hindering the restoration process by freezing the mobile application.

![Screenshot_20240105_195738](https://github.com/kodjodevf/mangayomi/assets/104534608/b7228f20-946b-4211-9372-a6ab59e1af9f)

### Mangayomi version

(Beta) - 0.1.55

### Device

Samsung Galaxy a21 

### Other details

I  kindly request your assistance in investigating and implementing a solution to enable MangaYomi to automatically recognize and restore backup files from Tachiyomi.This issue is crucial for users who are transitioning from Tachiyomi to MangaYomi, and a smooth backup restoration process is vital to ensure a positive user experience.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by leminhhien0301** [comment]
I want to report the same issue happen in desktop app (windows 10), mangayomi v0.1.61
