### ISSUE TITLE
Feature req#

### ISSUE THREAD

**Issue by knightmob** [kodjodevf/mangayomi#9]
Hi! I love your desktop app version! looks pretty slick, even better than tachidesk, in my opinion rather, but if you don't mind me asking some few things, although I know its still in beta stage but I just want to request a few features that I think will evolve your desktop app even better,

- Add a Translator filter, if you're not aware of it, its the thing you can find in tachiyomi android this thing, it will be a big help, especially for sources like comic since it catered different translation.
![Screenshot_2023_0606_103845](https://github.com/kodjodevf/mangayomi/assets/76065610/8e2e08be-b9b7-4d0b-943a-179dd3bf5e43)

- secondly, I suggest you add some trackers, its fine if its only anilist.
![Screenshot_2023_0606_103910](https://github.com/kodjodevf/mangayomi/assets/76065610/63ef7c5a-55ec-4734-b619-cdcccf08fa53)

overall, the desktop app looks promising, keep up the great work.

**Comment by kodjodevf** [comment]
Noted The Translator filter has been added

**Comment by kodjodevf** [comment]
The Anilist tracker has been added
