### ISSUE TITLE
Torrent Streaming Support

### ISSUE THREAD

**Issue by smurat** [kodjodevf/mangayomi#94]
### Describe your suggested feature

First of all, I love the app, great project with a lot of potential.

Can you add torrent streaming like in [miruproject](https://github.com/miru-project/miru-app).
The [BtServer](https://github.com/miru-project/bt-server) repo could be helpful in implementing this feature.

I think this project could be a good alternative to Stremio with this feature.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.

**Comment by kodjodevf** [comment]
Added !!
