### ISSUE TITLE
The Appimage does not run on Ubuntu 22.04

### ISSUE THREAD

**Issue by dtantono** [kodjodevf/mangayomi#95]
### Steps to reproduce

1. Double click the app
2. it does not run

### Expected behavior

it should work

### Actual behavior

I got error message
![image](https://github.com/kodjodevf/mangayomi/assets/29157187/e22220c6-0b4c-4195-a84f-0c5744076fd3)

### Mangayomi version

v0.1.61

### Device

Ubuntu 22.04

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by dtantono** [comment]
oh, I got same error message on SteamOS as well

**Comment by kodjodevf** [comment]
Use this cmd : sudo apt-get install webkit2gtk-4.1

**Comment by dtantono** [comment]
Thanks, for Ubuntu side it works. How about for SteamOS as a derivative of archlinux?
