### ISSUE TITLE
Having the same subtitles and resources?

### ISSUE THREAD

**Issue by lavara123** [kodjodevf/mangayomi#99]
### Steps to reproduce

Video player 

### Expected behavior

to be unique

### Actual behavior

Having the same subtitles and resources

### Mangayomi version

Last 

### Device

Nubia Red Magic 8 Pro

### Other details

Android video player
And the design of this part can be made more beautiful

![Screenshot_2024-01-14-15-02-24-849](https://github.com/kodjodevf/mangayomi/assets/12005386/d79d300b-d07d-4232-a93b-9f0ba8f09b5c)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by kodjodevf** [comment]
Fixed !
